// ============================================
// src/roman_mapping.rs (新規ファイル)
// ============================================

use std::collections::HashMap;

pub fn create_roman_mapping() -> HashMap<&'static str, Vec<&'static str>> {
    let mut map: HashMap<&'static str, Vec<&'static str>> = HashMap::new();

    map.insert("あ", vec!["a"]);
    map.insert("い", vec!["i", "yi"]);
    map.insert("う", vec!["u", "wu", "whu"]);
    map.insert("え", vec!["e"]);
    map.insert("お", vec!["o"]);
    map.insert("か", vec!["ka", "ca"]);
    map.insert("き", vec!["ki"]);
    map.insert("く", vec!["ku", "cu", "qu"]);
    map.insert("け", vec!["ke"]);
    map.insert("こ", vec!["ko", "co"]);
    map.insert("さ", vec!["sa"]);
    map.insert("し", vec!["si", "shi", "ci"]);
    map.insert("す", vec!["su"]);
    map.insert("せ", vec!["se", "ce"]);
    map.insert("そ", vec!["so"]);
    map.insert("た", vec!["ta"]);
    map.insert("ち", vec!["ti", "chi"]);
    map.insert("つ", vec!["tu", "tsu"]);
    map.insert("て", vec!["te"]);
    map.insert("と", vec!["to"]);
    map.insert("な", vec!["na"]);
    map.insert("に", vec!["ni"]);
    map.insert("ぬ", vec!["nu"]);
    map.insert("ね", vec!["ne"]);
    map.insert("の", vec!["no"]);
    map.insert("は", vec!["ha"]);
    map.insert("ひ", vec!["hi"]);
    map.insert("ふ", vec!["fu", "hu"]);
    map.insert("へ", vec!["he"]);
    map.insert("ほ", vec!["ho"]);
    map.insert("ま", vec!["ma"]);
    map.insert("み", vec!["mi"]);
    map.insert("む", vec!["mu"]);
    map.insert("め", vec!["me"]);
    map.insert("も", vec!["mo"]);
    map.insert("や", vec!["ya"]);
    map.insert("ゆ", vec!["yu"]);
    map.insert("よ", vec!["yo"]);
    map.insert("ら", vec!["ra"]);
    map.insert("り", vec!["ri"]);
    map.insert("る", vec!["ru"]);
    map.insert("れ", vec!["re"]);
    map.insert("ろ", vec!["ro"]);
    map.insert("わ", vec!["wa"]);
    map.insert("を", vec!["wo"]);
    map.insert("ん", vec!["nn", "xn"]);
    map.insert("が", vec!["ga"]);
    map.insert("ぎ", vec!["gi"]);
    map.insert("ぐ", vec!["gu"]);
    map.insert("げ", vec!["ge"]);
    map.insert("ご", vec!["go"]);
    map.insert("ざ", vec!["za"]);
    map.insert("じ", vec!["ji", "zi"]);
    map.insert("ず", vec!["zu"]);
    map.insert("ぜ", vec!["ze"]);
    map.insert("ぞ", vec!["zo"]);
    map.insert("だ", vec!["da"]);
    map.insert("ぢ", vec!["di"]);
    map.insert("づ", vec!["du"]);
    map.insert("で", vec!["de"]);
    map.insert("ど", vec!["do"]);
    map.insert("ば", vec!["ba"]);
    map.insert("び", vec!["bi"]);
    map.insert("ぶ", vec!["bu"]);
    map.insert("べ", vec!["be"]);
    map.insert("ぼ", vec!["bo"]);
    map.insert("ぱ", vec!["pa"]);
    map.insert("ぴ", vec!["pi"]);
    map.insert("ぷ", vec!["pu"]);
    map.insert("ぺ", vec!["pe"]);
    map.insert("ぽ", vec!["po"]);
    map.insert("ぁ", vec!["la", "xa"]);
    map.insert("ぃ", vec!["li", "xi", "lyi", "xyi"]);
    map.insert("ぅ", vec!["lu", "xu"]);
    map.insert("ぇ", vec!["le", "xe", "lye", "xye"]);
    map.insert("ぉ", vec!["lo", "xo"]);
    map.insert("ゃ", vec!["lya", "xya"]);
    map.insert("ゅ", vec!["lyu", "xyu"]);
    map.insert("ょ", vec!["lyo", "xyo"]);
    map.insert("っ", vec!["ltu", "ltsu", "xtu", "xtsu"]);
    map.insert("きゃ", vec!["kya", "kilya", "kixya"]);
    map.insert("きぃ", vec!["kyi", "kili", "kilyi", "kixi", "kixyi"]);
    map.insert("きゅ", vec!["kyu", "kilyu", "kixyu"]);
    map.insert("きぇ", vec!["kye", "kile", "kilye", "kixe", "kixye"]);
    map.insert("きょ", vec!["kyo", "kilyo", "kixyo"]);
    map.insert("ぎゃ", vec!["gya", "gilya", "gixya"]);
    map.insert("ぎぃ", vec!["gyi", "gili", "gilyi", "gixi", "gixyi"]);
    map.insert("ぎゅ", vec!["gyu", "gilyu", "gixyu"]);
    map.insert("ぎぇ", vec!["gye", "gile", "gilye", "gixe", "gixye"]);
    map.insert("ぎょ", vec!["gyo", "gilyo", "gixyo"]);
    map.insert("くぁ", vec!["qa", "kwa", "kula", "kuxa", "cula", "cuxa", "qula", "quxa"]);
    map.insert("くぃ", vec!["qi", "qyi", "kuli", "kuxi", "kulyi", "kuxyi", "culi", "culyi", "cuxi", "cuxyi", "quli", "quxi", "qulyi", "quxyi"]);
    map.insert("くぅ", vec!["qwu", "kulu", "kuxu", "culu", "cuxu", "qulu", "quxu"]);
    map.insert("くぇ", vec!["qe", "qwe", "kule", "kuxe", "kulye", "kuxye", "cule", "cuxe", "culye", "cuxye", "qule", "quxe", "qulye", "quxye"]);
    map.insert("くぉ", vec!["qo", "qwo", "kulo", "kuxo", "culo", "cuxo", "qulo", "quxo"]);
    map.insert("ぐぁ", vec!["gwa", "gula", "guxa"]);
    map.insert("ぐぃ", vec!["gwi", "guli", "gulyi", "guxi", "guxyi"]);
    map.insert("ぐぅ", vec!["gwu", "gulu", "guxu"]);
    map.insert("ぐぇ", vec!["gwe", "gule", "guxe", "gulye", "guxye"]);
    map.insert("ぐぉ", vec!["gwo", "gulo", "guxo"]);
    map.insert("しゃ", vec!["sya", "sha", "silya", "sixya", "shilya", "shixya", "cilya", "cixya"]);
    map.insert("しぃ", vec!["syi", "sili", "sixi", "silyi", "sixyi", "shili", "shixi", "shilyi", "shixyi", "cili", "cixi", "cilyi", "cixyi"]);
    map.insert("しゅ", vec!["syu", "shu", "silyu", "sixyu", "shilyu", "shixyu", "cilyu", "cixyu"]);
    map.insert("しぇ", vec!["sye", "she", "sile", "silye", "sixe", "sixye", "shile", "shilye", "shixe", "shixye", "cile", "cilye", "cixe", "cixye"]);
    map.insert("しょ", vec!["syo", "sho", "silyo", "sixyo", "shilyo", "shixyo", "cilyo", "cixyo"]);
    map.insert("じゃ", vec!["ja", "jya", "zya", "jilya", "jixya", "zilya", "zixya"]);
    map.insert("じぃ", vec!["jyi", "zyi", "jili", "jixi", "jilyi", "jixyi", "zili", "zixi", "zilyi", "zixyi"]);
    map.insert("じゅ", vec!["ju", "jyu", "zyu", "jilyu", "jixyu", "zilyu", "zixyu"]);
    map.insert("じぇ", vec!["je", "jye", "zye", "jile", "jixe", "jilye", "jixye", "zile", "zixe", "zilye", "zixye"]);
    map.insert("じょ", vec!["jo", "jyo", "zyo", "jilyo", "jixyo", "zilyo", "zixyo"]);
    map.insert("すぁ", vec!["swa", "sula", "suxa"]);
    map.insert("すぃ", vec!["swi", "suli", "sulyi", "suxi", "suxyi"]);
    map.insert("すぅ", vec!["swu", "sulu", "suxu"]);
    map.insert("すぇ", vec!["swe", "sule", "suxe", "sulye", "suxye"]);
    map.insert("すぉ", vec!["swo", "sulo", "suxo"]);
    map.insert("ちゃ", vec!["tya", "cha", "cya", "tilya", "tixya", "chilya", "chixya"]);
    map.insert("ちぃ", vec!["tyi", "cyi", "tili", "tixi", "tilyi", "tixyi", "chili", "chixi", "chilyi", "chixyi"]);
    map.insert("ちゅ", vec!["tyu", "chu", "cyu", "tilyu", "tixyu", "chilyu", "chixyu"]);
    map.insert("ちぇ", vec!["tye", "che", "cye", "tile", "tixe", "tilye", "tixye", "chile", "chixe", "chilye", "chixye"]);
    map.insert("ちょ", vec!["tyo", "cho", "cyo", "tilyo", "tixyo", "chilyo", "chixyo"]);
    map.insert("ぢゃ", vec!["dya", "dilya", "dixya"]);
    map.insert("ぢぃ", vec!["dyi", "dilyi", "dixyi"]);
    map.insert("ぢゅ", vec!["dyu", "dilyu", "dixyu"]);
    map.insert("ぢぇ", vec!["dye", "dile", "dixe", "dilye", "dixye"]);
    map.insert("ぢょ", vec!["dyo", "dilyo", "dixyo"]);
    map.insert("つぁ", vec!["tsa", "tula", "tuxa", "tsula", "tsuxa"]);
    map.insert("つぃ", vec!["tsi", "tuli", "tuxi", "tulyi", "tuxyi", "tsuli", "tsuxi", "tsulyi", "tsuxyi"]);
    map.insert("つぇ", vec!["tse", "tule", "tuxe", "tulye", "tuxye", "tsule", "tsuxe", "tsulye", "tsuxye"]);
    map.insert("つぉ", vec!["tso", "tulo", "tuxo", "tsulo", "tsuxo"]);
    map.insert("てゃ", vec!["tha", "telya", "texya"]);
    map.insert("てぃ", vec!["thi", "teli", "texi", "telyi", "texyi"]);
    map.insert("てゅ", vec!["thu", "telyu", "texyu"]);
    map.insert("てぇ", vec!["the", "tele", "texe", "telye", "texye"]);
    map.insert("てょ", vec!["tho", "telyo", "texyo"]);
    map.insert("でゃ", vec!["dha", "delya", "dexya"]);
    map.insert("でぃ", vec!["dhi", "deli", "dexi", "delyi", "dexyi"]);
    map.insert("でゅ", vec!["dhu", "delyu", "dexyu"]);
    map.insert("でぇ", vec!["dhe", "dele", "dexe", "delye", "dexye"]);
    map.insert("でょ", vec!["dho", "delyo", "dexyo"]);
    map.insert("とぁ", vec!["twa", "tola", "toxa"]);
    map.insert("とぃ", vec!["twi", "toli", "toxi", "tolyi", "toxyi"]);
    map.insert("とぅ", vec!["twu", "tolu", "toxu"]);
    map.insert("とぇ", vec!["twe", "tole", "toxe", "tolye", "toxye"]);
    map.insert("とぉ", vec!["two", "tolo", "toxo"]);
    map.insert("どぁ", vec!["dwa", "dola", "doxa"]);
    map.insert("どぃ", vec!["dwi", "doli", "doxi", "dolyi", "doxyi"]);
    map.insert("どぅ", vec!["dwu", "dolu", "doxu"]);
    map.insert("どぇ", vec!["dwe", "dole", "doxe", "dolye", "doxye"]);
    map.insert("どぉ", vec!["dwo", "dolo", "doxo"]);
    map.insert("にゃ", vec!["nya", "nilya", "nixya"]);
    map.insert("にぃ", vec!["nyi", "nili", "nixi", "nilyi", "nixyi"]);
    map.insert("にゅ", vec!["nyu", "nilyu", "nixyu"]);
    map.insert("にぇ", vec!["nye", "nile", "nixe", "nilye", "nixye"]);
    map.insert("にょ", vec!["nyo", "nilyo", "nixyo"]);
    map.insert("ぴゃ", vec!["pya", "pilya", "pixya"]);
    map.insert("ぴぃ", vec!["pyi", "pili", "pixi", "pilyi", "pixyi"]);
    map.insert("ぴゅ", vec!["pyu", "pilyu", "pixyu"]);
    map.insert("ぴぇ", vec!["pye", "pile", "pixe", "pilye", "pixye"]);
    map.insert("ぴょ", vec!["pyo", "pilyo", "pixyo"]);
    map.insert("ひゃ", vec!["hya", "hilya", "hixya"]);
    map.insert("ひぃ", vec!["hyi", "hili", "hixi", "hilyi", "hixyi"]);
    map.insert("ひゅ", vec!["hyu", "hilyu", "hixyu"]);
    map.insert("ひぇ", vec!["hye", "hile", "hixe", "hilye", "hixye"]);
    map.insert("ひょ", vec!["hyo", "hilyo", "hixyo"]);
    map.insert("びゃ", vec!["bya", "bilya", "bixya"]);
    map.insert("びぃ", vec!["byi", "bili", "bixi", "bilyi", "bixyi"]);
    map.insert("びゅ", vec!["byu", "bilyu", "bixyu"]);
    map.insert("びぇ", vec!["bye", "bile", "bixe", "bilye", "bixye"]);
    map.insert("びょ", vec!["byo", "bilyo", "bixyo"]);
    map.insert("ふゃ", vec!["fya", "fulya", "fuxya", "hulya", "huxya"]);
    map.insert("ふぃ", vec!["fi", "fyi", "fuli", "fuxi", "fulyi", "fuxyi", "huli", "huxi", "hulyi", "huxyi"]);
    map.insert("ふゅ", vec!["fyu", "fulyu", "fuxyu", "hulyu", "huxyu"]);
    map.insert("ふぇ", vec!["fe", "fye", "fule", "fuxe", "fulye", "fuxye", "hule", "huxe", "hulye", "huxye"]);
    map.insert("ふょ", vec!["fyo", "fulyo", "fuxyo", "hulyo", "huxyo"]);
    map.insert("ふぁ", vec!["fa", "fula", "fuxa", "hula", "huxa"]);
    map.insert("ふぉ", vec!["fo", "fulo", "fuxo", "hulo", "huxo"]);
    map.insert("みゃ", vec!["mya", "milya", "mixya"]);
    map.insert("みぃ", vec!["myi", "mili", "mixi", "milyi", "mixyi"]);
    map.insert("みゅ", vec!["myu", "milyu", "mixyu"]);
    map.insert("みぇ", vec!["mye", "mile", "mixe", "milye", "mixye"]);
    map.insert("みょ", vec!["myo", "milyo", "mixyo"]);
    map.insert("りゃ", vec!["rya", "rilya", "rixya"]);
    map.insert("りぃ", vec!["ryi", "rili", "rixi", "rilyi", "rixyi"]);
    map.insert("りゅ", vec!["ryu", "rilyu", "rixyu"]);
    map.insert("りぇ", vec!["rye", "rile", "rixe", "rilye", "rixye"]);
    map.insert("りょ", vec!["ryo", "rilyo", "rixyo"]);
    map.insert("うぁ", vec!["wha", "ula", "uxa", "wula", "wuxa", "whula", "whuxa"]);
    map.insert("うぃ", vec!["wi", "whi", "uli", "uxi", "ulyi", "uxyi", "wuli", "wuxi", "wulyi", "wuxyi", "whuli"]);
    map.insert("うぇ", vec!["we", "whe", "ule", "uxe", "ulye", "uxye", "wule", "wuxe", "wulye", "wuxye", "whule", "whuxe", "whulye", "whuxye"]);
    map.insert("うぉ", vec!["who", "ulo", "uxo", "wulo", "wuxo", "whulo", "whuxo"]);
    map.insert("ゔぁ", vec!["va", "vula", "vuxa"]);
    map.insert("ゔぃ", vec!["vi", "vyi", "vuli", "vuxi", "vulyi", "vuxyi"]);
    map.insert("ゔ", vec!["vu"]);
    map.insert("ゔぇ", vec!["ve", "vye", "vule", "vuxe", "vulye", "vuxye"]);
    map.insert("ゔぉ", vec!["vo", "vulo", "vuxo"]);
    map.insert("ゔゃ", vec!["vya", "vulya", "vuxya"]);
    map.insert("ゔゅ", vec!["vyu", "vulyu", "vuxyu"]);
    map.insert("ゔょ", vec!["vyo", "vulyo", "vuxyo"]);
    map.insert("ヴぁ", vec!["va", "vula", "vuxa"]);
    map.insert("ヴぃ", vec!["vi", "vyi", "vuli", "vuxi", "vulyi", "vuxyi"]);
    map.insert("ヴ", vec!["vu"]);
    map.insert("ヴぇ", vec!["ve", "vye", "vule", "vuxe", "vulye", "vuxye"]);
    map.insert("ヴぉ", vec!["vo", "vulo", "vuxo"]);
    map.insert("ヴゃ", vec!["vya", "vulya", "vuxya"]);
    map.insert("ヴゅ", vec!["vyu", "vulyu", "vuxyu"]);
    map.insert("ヴょ", vec!["vyo", "vulyo", "vuxyo"]);
    map.insert("ゐ", vec!["wyi"]);
    map.insert("ゑ", vec!["wye"]);
    map.insert("んか", vec!["nka", "nca", "nnka", "nnca", "xnka", "xnca"]);
    map.insert("んき", vec!["nki", "nnki", "xnki"]);
    map.insert("んく", vec!["nku", "ncu", "nqu", "nnku", "nncu", "nnqu", "xnku", "xncu", "xnqu"]);
    map.insert("んけ", vec!["nke", "nnke", "xnke"]);
    map.insert("んこ", vec!["nko", "nco", "nnko", "nnco", "xnko", "xnco"]);
    map.insert("んさ", vec!["nsa", "nnsa", "xnsa"]);
    map.insert("んし", vec!["nsi", "nshi", "nci", "nnsi", "nnshi", "nnci", "xnsi", "xnshi", "xnci"]);
    map.insert("んす", vec!["nsu", "nnsu", "xnsu"]);
    map.insert("んせ", vec!["nse", "nce", "nnse", "nnce", "xnse", "xnce"]);
    map.insert("んそ", vec!["nso", "nnso", "xnso"]);
    map.insert("んた", vec!["nta", "nnta", "xnta"]);
    map.insert("んち", vec!["nti", "nchi", "nnti", "nnchi", "xnti", "xnchi"]);
    map.insert("んつ", vec!["ntu", "ntsu", "nntu", "nntsu", "xntu", "xntsu"]);
    map.insert("んて", vec!["nte", "nnte", "xnte"]);
    map.insert("んと", vec!["nto", "nnto", "xnto"]);
    map.insert("んは", vec!["nha", "nnha", "xnha"]);
    map.insert("んひ", vec!["nhi", "nnhi", "xnhi"]);
    map.insert("んふ", vec!["nfu", "nhu", "nnfu", "nnhu", "xnfu", "xnhu"]);
    map.insert("んへ", vec!["nhe", "nnhe", "xnhe"]);
    map.insert("んほ", vec!["nho", "nnho", "xnho"]);
    map.insert("んま", vec!["nma", "nnma", "xnma"]);
    map.insert("んみ", vec!["nmi", "nnmi", "xnmi"]);
    map.insert("んむ", vec!["nmu", "nnmu", "xnmu"]);
    map.insert("んめ", vec!["nme", "nnme", "xnme"]);
    map.insert("んも", vec!["nmo", "nnmo", "xnmo"]);
    map.insert("んら", vec!["nra", "nnra", "xnra"]);
    map.insert("んり", vec!["nri", "nnri", "xnri"]);
    map.insert("んる", vec!["nru", "nnru", "xnru"]);
    map.insert("んれ", vec!["nre", "nnre", "xnre"]);
    map.insert("んろ", vec!["nro", "nnro", "xnro"]);
    map.insert("んわ", vec!["nwa", "nnwa", "xnwa"]);
    map.insert("んを", vec!["nwo", "nnwo", "xnwo"]);
    map.insert("んが", vec!["nga", "nnga", "xnga"]);
    map.insert("んぎ", vec!["ngi", "nngi", "xngi"]);
    map.insert("んぐ", vec!["ngu", "nngu", "xngu"]);
    map.insert("んげ", vec!["nge", "nnge", "xnge"]);
    map.insert("んご", vec!["ngo", "nngo", "xngo"]);
    map.insert("んざ", vec!["nza", "nnza", "xnza"]);
    map.insert("んじ", vec!["nji", "nzi", "nnji", "nnzi", "xnji", "xnzi"]);
    map.insert("んず", vec!["nzu", "nnzu", "xnzu"]);
    map.insert("んぜ", vec!["nze", "nnze", "xnze"]);
    map.insert("んぞ", vec!["nzo", "nnzo", "xnze"]);
    map.insert("んだ", vec!["nda", "nnda", "xnda"]);
    map.insert("んぢ", vec!["ndi", "nndi", "xndi"]);
    map.insert("んづ", vec!["ndu", "nndu", "xndu"]);
    map.insert("んで", vec!["nde", "nnde", "xnde"]);
    map.insert("んど", vec!["ndo", "nndo", "xndo"]);
    map.insert("んば", vec!["nba", "nnba", "xnba"]);
    map.insert("んび", vec!["nbi", "nnbi", "xnbi"]);
    map.insert("んぶ", vec!["nbu", "nnbu", "xnbu"]);
    map.insert("んべ", vec!["nbe", "nnbe", "xnbe"]);
    map.insert("んぼ", vec!["nbo", "nnbo", "xnbo"]);
    map.insert("んぱ", vec!["npa", "nnpa", "xnpa"]);
    map.insert("んぴ", vec!["npi", "nnpi", "xnpi"]);
    map.insert("んぷ", vec!["npu", "nnpu", "xnpu"]);
    map.insert("んぺ", vec!["npe", "nnpe", "xnpe"]);
    map.insert("んぽ", vec!["npo", "nnpo", "xnpo"]);
    map.insert("んきゃ", vec!["nkya", "nkilya", "nkixya", "nnkya", "nnkilya", "nnkixya", "xnkya", "xnkilya", "xnkixya"]);
    map.insert("んきぃ", vec!["nkyi", "nkili", "nkilyi", "nkixi", "nkixyi", "nnkyi", "nnkili", "nnkilyi", "nnkixi", "nnkixyi", "xnkyi", "xnkili", "xnkilyi", "xnkixi", "xnkixyi"]);
    map.insert("んきゅ", vec!["nkyu", "nkilyu", "nkixyu", "nnkyu", "nnkilyu", "nnkixyu", "xnkyu", "xnkilyu", "xnkixyu"]);
    map.insert("んきぇ", vec!["nkye", "nkile", "nkilye", "nkixe", "nkixye", "nnkye", "nnkile", "nnkilye", "nnkixe", "nnkixye", "xnkye", "xnkile", "xnkilye", "xnkixe", "xnkixye"]);
    map.insert("んきょ", vec!["nkyo", "nkilyo", "nkixyo", "nnkyo", "nnkilyo", "nnkixyo", "xnkyo", "xnkilyo", "xnkixyo"]);
    map.insert("んぎゃ", vec!["ngya", "ngilya", "ngixya", "nngya", "nngilya", "nngixya", "xngya", "xngilya", "xngixya"]);
    map.insert("んぎぃ", vec!["ngyi", "ngili", "ngilyi", "ngixi", "ngixyi", "nngyi", "nngili", "nngilyi", "nngixi", "nngixyi", "xngyi", "xngili", "xngilyi", "xngixi", "xngixyi"]);
    map.insert("んぎゅ", vec!["ngyu", "ngilyu", "ngixyu", "nngyu", "nngilyu", "nngixyu", "xngyu", "xngilyu", "xngixyu"]);
    map.insert("んぎぇ", vec!["ngye", "ngile", "ngilye", "ngixe", "ngixye", "nngye", "nngile", "nngilye", "nngixe", "nngixye", "xngye", "xngile", "xngilye", "xngixe", "xngixye"]);
    map.insert("んぎょ", vec!["ngyo", "ngilyo", "ngixyo", "nngyo", "nngilyo", "nngixyo", "xngyo", "xngilyo", "xngixyo"]);
    map.insert("んしゃ", vec!["nsya", "nsha", "nsilya", "nsixya", "nshilya", "nshixya", "ncilya", "ncixya", "nnsya", "nnsha", "nnsilya", "nnsixya", "nnshilya", "nnshixya", "nncilya", "nncixya", "xnsya", "xnsha", "xnsilya", "xnsixya", "xnshilya", "xnshixya", "xncilya", "xncixya"]);
    map.insert("んしぃ", vec!["nsyi", "nsili", "nsixi", "nsilyi", "nsixyi", "nshili", "nshixi", "nshilyi", "nshixyi", "ncili", "ncixi", "ncilyi", "ncixyi", "nnsyi", "nnsili", "nnsixi", "nnsilyi", "nnsixyi", "nnshili", "nnshixi", "nnshilyi", "nnshixyi", "nncili", "nncixi", "nncilyi", "nncixyi", "xnsyi", "xnsili", "xnsixi", "xnsilyi", "xnsixyi", "xnshili", "xnshixi", "xnshilyi", "xnshixyi", "xncili", "xncixi", "xncilyi", "xncixyi"]);
    map.insert("んしゅ", vec!["nsyu", "nshu", "nsilyu", "nsixyu", "nshilyu", "nshixyu", "ncilyu", "ncixyu", "nnsyu", "nnshu", "nnsilyu", "nnsixyu", "nnshilyu", "nnshixyu", "nncilyu", "nncixyu", "xnsyu", "xnshu", "xnsilyu", "xnsixyu", "xnshilyu", "xnshixyu", "xncilyu", "xncixyu"]);
    map.insert("んしぇ", vec!["nsye", "nshe", "nsile", "nsilye", "nsixe", "nsixye", "nshile", "nshilye", "nshixe", "nshixye", "ncile", "ncilye", "ncixe", "ncixye", "nnsye", "nnshe", "nnsile", "nnsilye", "nnsixe", "nnsixye", "nnshile", "nnshilye", "nnshixe", "nnshixye", "nncile", "nncilye", "nncixe", "nncixye", "xnsye", "xnshe", "xnsile", "xnsilye", "xnsixe", "xnsixye", "xnshile", "xnshilye", "xnshixe", "xnshixye", "xncile", "xncilye", "xncixe", "xncixye"]);
    map.insert("んしょ", vec!["nsyo", "nsho", "nsilyo", "nsixyo", "nshilyo", "nshixyo", "ncilyo", "ncixyo", "nnsyo", "nnsho", "nnsilyo", "nnsixyo", "nnshilyo", "nnshixyo", "nncilyo", "nncixyo", "xnsyo", "xnsho", "xnsilyo", "xnsixyo", "xnshilyo", "xnshixyo", "xncilyo", "xncixyo"]);
    map.insert("んじゃ", vec!["nja", "njya", "nzya", "njilya", "njixya", "nzilya", "nzixya", "nnja", "nnjya", "nnzya", "nnjilya", "nnjixya", "nnzilya", "nnzixya", "xnja", "xnjya", "xnzya", "xnjilya", "xnjixya", "xnzilya", "xnzixya"]);
    map.insert("んじぃ", vec!["njyi", "nzyi", "njili", "njixi", "njilyi", "njixyi", "nzili", "nzixi", "nzilyi", "nzixyi", "nnjyi", "nnzyi", "nnjili", "nnjixi", "nnjilyi", "nnjixyi", "nnzili", "nnzixi", "nnzilyi", "nnzixyi", "xnjyi", "xnzyi", "xnjili", "xnjixi", "xnjilyi", "xnjixyi", "xnzili", "xnzixi", "xnzilyi", "xnzixyi"]);
    map.insert("んじゅ", vec!["nju", "njyu", "nzyu", "njilyu", "njixyu", "nzilyu", "nzixyu", "nnju", "nnjyu", "nnzyu", "nnjilyu", "nnjixyu", "nnzilyu", "nnzixyu", "xnju", "xnjyu", "xnzyu", "xnjilyu", "xnjixyu", "xnzilyu", "xnzixyu"]);
    map.insert("んじぇ", vec!["nje", "njye", "nzye", "njile", "njixe", "njilye", "njixye", "nzile", "nzixe", "nzilye", "nzixye", "nnje", "nnjye", "nnzye", "nnjile", "nnjixe", "nnjilye", "nnjixye", "nnzile", "nnzixe", "nnzilye", "nnzixye", "xnje", "xnjye", "xnzye", "xnjile", "xnjixe", "xnjilye", "xnjixye", "xnzile", "xnzixe", "xnzilye", "xnzixye"]);
    map.insert("んじょ", vec!["njo", "njyo", "nzyo", "njilyo", "njixyo", "nzilyo", "nzixyo", "nnjo", "nnjyo", "nnzyo", "nnjilyo", "nnjixyo", "nnzilyo", "nnzixyo", "xnjo", "xnjyo", "xnzyo", "xnjilyo", "xnjixyo", "xnzilyo", "xnzixyo"]);
    map.insert("んちゃ", vec!["ntya", "ncha", "ncya", "ntilya", "ntixya", "nchilya", "nchixya", "nntya", "nncha", "nncya", "nntilya", "nntixya", "nnchilya", "nnchixya", "xntya", "xncha", "xncya", "xntilya", "xntixya", "xnchilya", "xnchixya"]);
    map.insert("んちぃ", vec!["ntyi", "ncyi", "ntili", "ntixi", "ntilyi", "ntixyi", "nchili", "nchixi", "nchilyi", "nchixyi", "nntyi", "nncyi", "nntili", "nntixi", "nntilyi", "nntixyi", "nnchili", "nnchixi", "nnchilyi", "nnchixyi", "xntyi", "xncyi", "xntili", "xntixi", "xntilyi", "xntixyi", "xnchili", "xnchixi", "xnchilyi", "xnchixyi"]);
    map.insert("んちゅ", vec!["ntyu", "nchu", "ncyu", "ntilyu", "ntixyu", "nchilyu", "nchixyu", "nntyu", "nnchu", "nncyu", "nntilyu", "nntixyu", "nnchilyu", "nnchixyu", "xntyu", "xnchu", "xncyu", "xntilyu", "xntixyu", "xnchilyu", "xnchixyu"]);
    map.insert("んちぇ", vec!["ntye", "nche", "ncye", "ntile", "ntixe", "ntilye", "ntixye", "nchile", "nchixe", "nchilye", "nchixye", "nntye", "nnche", "nncye", "nntile", "nntixe", "nntilye", "nntixye", "nnchile", "nnchixe", "nnhilye", "nnchixye", "xntye", "xnche", "xncye", "xntile", "xntixe", "xntilye", "xntixye", "xnchile", "xnchixe", "xnchilye", "xnchixye"]);
    map.insert("んちょ", vec!["ntyo", "ncho", "ncyo", "ntilyo", "ntixyo", "nchilyo", "nchixyo", "nntyo", "nncho", "nncyo", "nntilyo", "nntixyo", "nnchilyo", "nnchixyo", "xntyo", "xncho", "xncyo", "xntilyo", "xntixyo", "xnchilyo", "xnchixyo"]);
    map.insert("んぢぃ", vec!["ndyi", "nndyi", "xndyi", "ndilyi", "nndilyi", "xndilyi", "ndixyi", "nndixyi", "xndixyi"]);
    map.insert("んぢゃ", vec!["ndya", "ndilya", "ndixya", "nndya", "nndilya", "nndixya", "xndya", "xndilya", "xndixya"]);
    map.insert("んぢゅ", vec!["ndyu", "ndilyu", "ndixyu", "nndyu", "nndilyu", "nndixyu", "xndyu", "xndilyu", "xndixyu"]);
    map.insert("んぢぇ", vec!["ndye", "ndile", "ndixe", "ndilye", "ndixye", "nndye", "nndile", "nndixe", "nndilye", "nndixye", "xndye", "xndile", "xndixe", "xndilye", "xndixye"]);
    map.insert("んぢょ", vec!["ndyo", "ndilyo", "ndixyo", "nndyo", "nndilyo", "nndixyo", "xndyo", "xndilyo", "xndixyo"]);
    map.insert("んつぁ", vec!["ntsa", "ntula", "ntuxa", "ntsula", "ntsuxa", "nntsa", "nntula", "nntuxa", "nntsula", "nntsuxa", "xntsa", "xntula", "xntuxa", "xntsula", "xntsuxa"]);
    map.insert("んつぃ", vec!["ntsi", "ntuli", "ntuxi", "ntulyi", "ntuxyi", "ntsuli", "ntsuxi", "ntsulyi", "ntsuxyi", "nntsi", "nntuli", "nntuxi", "nntulyi", "nntuxyi", "nntsuli", "nntsuxi", "nntsulyi", "nntsuxyi", "xntsi", "xntuli", "xntuxi", "xntulyi", "xntuxyi", "xntsuli", "xntsuxi", "xntsulyi", "xntsuxyi"]);
    map.insert("んつぇ", vec!["ntse", "ntule", "ntuxe", "ntulye", "ntuxye", "ntsule", "ntsuxe", "ntsulye", "ntsuxye", "nntse", "nntule", "nntuxe", "nntulye", "nntuxye", "nntsule", "nntsuxe", "nntsulye", "nntsuxye", "xntse", "xntule", "xntuxe", "xntulye", "xntuxye", "xntsule", "xntsuxe", "xntsulye", "xntsuxye"]);
    map.insert("んつぉ", vec!["ntso", "ntulo", "ntuxo", "ntsulo", "ntsuxo", "nntso", "nntulo", "nntuxo", "nntsulo", "nntsuxo", "xntso", "xntulo", "xntuxo", "xntsulo", "xntsuxo"]);
    map.insert("んてゃ", vec!["ntha", "ntelya", "ntexya", "nntha", "nntelya", "nntexya", "xntha", "xntelya", "xntexya"]);
    map.insert("んてぃ", vec!["nthi", "nteli", "ntexi", "ntelyi", "ntexyi", "nnthi", "nnteli", "nntexi", "nntelyi", "nntexyi", "xnthi", "xnteli", "xntexi", "xntelyi", "xntexyi"]);
    map.insert("んてゅ", vec!["nthu", "ntelyu", "ntexyu", "nnthu", "nntelyu", "nntexyu", "xnthu", "xntelyu", "xntexyu"]);
    map.insert("んてぇ", vec!["nthe", "ntele", "ntexe", "ntelye", "ntexye", "nnthe", "nntele", "nntexe", "nntelye", "nntexye", "xnthe", "xntele", "xntexe", "xntelye", "xntexye"]);
    map.insert("んてょ", vec!["ntho", "ntelyo", "ntexyo", "nntho", "nntelyo", "nntexyo", "xntho", "xntelyo", "xntexyo"]);
    map.insert("んでゃ", vec!["ndha", "ndelya", "ndexya", "nndha", "nndelya", "nndexya", "xndha", "xndelya", "xndexya"]);
    map.insert("んでぃ", vec!["ndhi", "ndeli", "ndexi", "ndelyi", "ndexyi", "nndhi", "nndeli", "nndexi", "nndelyi", "nndexyi", "xndhi", "xndeli", "xndexi", "xndelyi", "xndexyi"]);
    map.insert("んでゅ", vec!["ndhu", "ndelyu", "ndexyu", "nndhu", "nndelyu", "nndexyu", "xndhu", "xndelyu", "xndexyu"]);
    map.insert("んでぇ", vec!["ndhe", "ndele", "ndexe", "ndelye", "ndexye", "nndhe", "nndele", "nndexe", "nndelye", "nndexye", "xndhe", "xndele", "xndexe", "xndelye", "xndexye"]);
    map.insert("んでょ", vec!["ndho", "ndelyo", "ndexyo", "nndho", "nndelyo", "nndexyo", "xndho", "xndelyo", "xndexyo"]);
    map.insert("んとぁ", vec!["ntwa", "ntola", "ntoxa", "nntwa", "nntola", "nntoxa", "xntwa", "xntola", "xntoxa"]);
    map.insert("んとぃ", vec!["ntwi", "ntoli", "ntoxi", "ntolyi", "ntoxyi", "nntwi", "nntoli", "nntoxi", "nntolyi", "nntoxyi", "xntwi", "xntoli", "xntoxi", "xntolyi", "xntoxyi"]);
    map.insert("んとぅ", vec!["ntwu", "ntolu", "ntoxu", "nntwu", "nntolu", "nntoxu", "xntwu", "xntolu", "xntoxu"]);
    map.insert("んとぇ", vec!["ntwe", "ntole", "ntoxe", "ntolye", "ntoxye", "nntwe", "nntole", "nntoxe", "nntolye", "nntoxye", "xntwe", "xntole", "xntoxe", "xntolye", "xntoxye"]);
    map.insert("んとぉ", vec!["ntwo", "ntolo", "ntoxo", "nntwo", "nntolo", "nntoxo", "xntwo", "xntolo", "xntoxo"]);
    map.insert("んどぁ", vec!["ndwa", "ndola", "ndoxa", "nndwa", "nndola", "nndoxa", "xndwa", "xndola", "xndoxa"]);
    map.insert("んどぃ", vec!["ndwi", "ndoli", "ndoxi", "ndolyi", "ndoxyi", "nndwi", "nndoli", "nndoxi", "nndolyi", "nndoxyi", "xndwi", "xndoli", "xndoxi", "xndolyi", "xndoxyi"]);
    map.insert("んどぅ", vec!["ndwu", "ndolu", "ndoxu", "nndwu", "nndolu", "nndoxu", "xndwu", "xndolu", "xndoxu"]);
    map.insert("んどぇ", vec!["ndwe", "ndole", "ndoxe", "ndolye", "ndoxye", "nndwe", "nndole", "nndoxe", "nndolye", "nndoxye", "xndwe", "xndole", "xndoxe", "xndolye", "xndoxye"]);
    map.insert("んどぉ", vec!["ndwo", "ndolo", "ndoxo", "nndwo", "nndolo", "nndoxo", "xndwo", "xndolo", "xndoxo"]);
    map.insert("んぴゃ", vec!["npya", "npilya", "npixya", "nnpya", "nnpilya", "nnpixya", "xnpya", "xnpilya", "xnpixya"]);
    map.insert("んぴぃ", vec!["npyi", "npili", "npixi", "npilyi", "npixyi", "nnpyi", "nnpili", "nnpixi", "nnpilyi", "nnpixyi", "xnpyi", "xnpili", "xnpixi", "xnpilyi", "xnpixyi"]);
    map.insert("んぴゅ", vec!["npyu", "npilyu", "npixyu", "nnpyu", "nnpilyu", "nnpixyu", "xnpyu", "xnpilyu", "xnpixyu"]);
    map.insert("んぴぇ", vec!["npye", "npile", "npixe", "npilye", "npixye", "nnpye", "nnpile", "nnpixe", "nnpilye", "nnpixye", "xnpye", "xnpile", "xnpixe", "xnpilye", "xnpixye"]);
    map.insert("んぴょ", vec!["npyo", "npilyo", "npixyo", "nnpyo", "nnpilyo", "nnpixyo", "xnpyo", "xnpilyo", "xnpixyo"]);
    map.insert("んひゃ", vec!["nhya", "nhilya", "nhixya", "nnhya", "nnhilya", "nnhixya", "xnhya", "xnhilya", "xnhixya"]);
    map.insert("んひぃ", vec!["nhyi", "nhili", "nhixi", "nhilyi", "nhixyi", "nnhyi", "nnhili", "nnhixi", "nnhilyi", "nnhixyi", "xnhyi", "xnhili", "xnhixi", "xnhilyi", "xnhixyi"]);
    map.insert("んひゅ", vec!["nhyu", "nhilyu", "nhixyu", "nnhyu", "nnhilyu", "nnhixyu", "xnhyu", "xnhilyu", "xnhixyu"]);
    map.insert("んひぇ", vec!["nhye", "nhile", "nhixe", "nhilye", "nhixye", "nnhye", "nnhile", "nnhixe", "nnhilye", "nnhixye", "xnhye", "xnhile", "xnhixe", "xnhilye", "xnhixye"]);
    map.insert("んひょ", vec!["nhyo", "nhilyo", "nhixyo", "nnhyo", "nnhilyo", "nnhixyo", "xnhyo", "xnhilyo", "xnhixyo"]);
    map.insert("んびゃ", vec!["nbya", "nbilya", "nbixya", "nnbya", "nnbilya", "nnbixya", "xnbya", "xnbilya", "xnbixya"]);
    map.insert("んびぃ", vec!["nbyi", "nbili", "nbixi", "nbilyi", "nbixyi", "nnbyi", "nnbili", "nnbixi", "nnbilyi", "nnbixyi", "xnbyi", "xnbili", "xnbixi", "xnbilyi", "xnbixyi"]);
    map.insert("んびゅ", vec!["nbyu", "nbilyu", "nbixyu", "nnbyu", "nnbilyu", "nnbixyu", "xnbyu", "xnbilyu", "xnbixyu"]);
    map.insert("んびぇ", vec!["nbye", "nbile", "nbixe", "nbilye", "nbixye", "nnbye", "nnbile", "nnbixe", "nnbilye", "nnbixye", "xnbye", "xnbile", "xnbixe", "xnbilye", "xnbixye"]);
    map.insert("んびょ", vec!["nbyo", "nbilyo", "nbixyo", "nnbyo", "nnbilyo", "nnbixyo", "xnbyo", "xnbilyo", "xnbixyo"]);
    map.insert("んふゃ", vec!["nfya", "nfulya", "nfuxya", "nhulya", "nhuxya", "nnfya", "nnfulya", "nnfuxya", "nnhulya", "nnhuxya", "xnfya", "xnfulya", "xnfuxya", "xnhulya", "xnhuxya"]);
    map.insert("んふぃ", vec!["nfi", "nfyi", "nfuli", "nfuxi", "nfulyi", "nfuxyi", "nhuli", "nhuxi", "nhulyi", "nhuxyi", "nnfi", "nnfyi", "nnfuli", "nnfuxi", "nnfulyi", "nnfuxyi", "nnhuli", "nnhuxi", "nnhulyi", "nnhuxyi", "xnfi", "xnfyi", "xnfuli", "xnfuxi", "xnfulyi", "xnfuxyi", "xnhuli", "xnhuxi", "xnhulyi", "xnhuxyi"]);
    map.insert("んふゅ", vec!["nfyu", "nfulyu", "nfuxyu", "nhulyu", "nhuxyu", "nnfyu", "nnfulyu", "nnfuxyu", "nnhulyu", "nnhuxyu", "xnfyu", "xnfulyu", "xnfuxyu", "xnhulyu", "xnhuxyu"]);
    map.insert("んふぇ", vec!["nfe", "nfye", "nfule", "nfuxe", "nfulye", "nfuxye", "nhule", "nhuxe", "nhulye", "nhuxye", "nnfe", "nnfye", "nnfule", "nnfuxe", "nnfulye", "nnfuxye", "nnhule", "nnhuxe", "nnhulye", "nnhuxye", "xnfe", "xnfye", "xnfule", "xnfuxe", "xnfulye", "xnfuxye", "xnhule", "xnhuxe", "xnhulye", "xnhuxye"]);
    map.insert("んふょ", vec!["nfyo", "nfulyo", "nfuxyo", "nhulyo", "nhuxyo", "nnfyo", "nnfulyo", "nnfuxyo", "nnhulyo", "nnhuxyo", "xnfyo", "xnfulyo", "xnfuxyo", "xnhulyo", "xnhuxyo"]);
    map.insert("んふぁ", vec!["nfa", "nfula", "nfuxa", "nhula", "nhuxa", "nnfa", "nnfula", "nnfuxa", "nnhula", "nnhuxa", "xnfa", "xnfula", "xnfuxa", "xnhula", "xnhuxa"]);
    map.insert("んふぉ", vec!["nfo", "nfulo", "nfuxo", "nhulo", "nhuxo", "nnfo", "nnfulo", "nnfuxo", "nnhulo", "nnhuxo", "xnfo", "xnfulo", "xnfuxo", "xnhulo", "xnhuxo"]);
    map.insert("んみゃ", vec!["nmya", "nmilya", "nmixya", "nnmya", "nnmilya", "nnmixya", "xnmya", "xnmilya", "xnmixya"]);
    map.insert("んみぃ", vec!["nmyi", "nmili", "nmixi", "nmilyi", "nmixyi", "nnmyi", "nnmili", "nnmixi", "nnmilyi", "nnmixyi", "xnmyi", "xnmili", "xnmixi", "xnmilyi", "xnmixyi"]);
    map.insert("んみゅ", vec!["nmyu", "nmilyu", "nmixyu", "nnmyu", "nnmilyu", "nnmixyu", "xnmyu", "xnmilyu", "xnmixyu"]);
    map.insert("んみぇ", vec!["nmye", "nmile", "nmixe", "nmilye", "nmixye", "nnmye", "nnmile", "nnmixe", "nnmilye", "nnmixye", "xnmye", "xnmile", "xnmixe", "xnilye", "xnmixye"]);
    map.insert("んみょ", vec!["nmyo", "nmilyo", "nmixyo", "nnmyo", "nnmilyo", "nnmixyo", "xnmyo", "xnmilyo", "xnmixyo"]);
    map.insert("んりゃ", vec!["nrya", "nrilya", "nrixya", "nnrya", "nnrilya", "nnrixya", "xnrya", "xnrilya", "xnrixya"]);
    map.insert("んりぃ", vec!["nryi", "nrili", "nrixi", "nrilyi", "nrixyi", "nnryi", "nnrili", "nnrixi", "nnrilyi", "nnrixyi", "xnryi", "xnrili", "xnrixi", "xnrilyi", "xnrixyi"]);
    map.insert("んりゅ", vec!["nryu", "nrilyu", "nrixyu", "nnryu", "nnrilyu", "nnrixyu", "xnryu", "xnrilyu", "xnrixyu"]);
    map.insert("んりぇ", vec!["nrye", "nrile", "nrixe", "nrilye", "nrixye", "nnrye", "nnrile", "nnrixe", "nnrilye", "nnrixye", "xnrye", "xnrile", "xnrixe", "xnrilye", "xnrixye"]);
    map.insert("んりょ", vec!["nryo", "nrilyo", "nrixyo", "nnryo", "nnrilyo", "nnrixyo", "xnryo", "xnrilyo", "xnrixyo"]);
    map.insert("んうぁ", vec!["nwha", "nula", "nuxa", "nwula", "nwuxa", "nwhula", "nwhuxa", "nnwha", "nnula", "nnuxa", "nnwula", "nnwuxa", "nnwhula", "nnwhuxa", "xnwha", "xnula", "xnuxa", "xnwula", "xnwuxa", "xnwhula", "xnwhuxa"]);
    map.insert("んうぃ", vec!["nwi", "nwhi", "nuli", "nuxi", "nulyi", "nuxyi", "nwuli", "nwuxi", "nwulyi", "nwuxyi", "nwhuli", "nnwi", "nnwhi", "nnuli", "nnuxi", "nnulyi", "nnuxyi", "nnwuli", "nnwuxi", "nnwulyi", "nnwuxyi", "nnwhuli", "xnwi", "xnwhi", "xnuli", "xnuxi", "xnulyi", "xnuxyi", "xnwuli", "xnwuxi", "xnwulyi", "xnwuxyi", "xnwhuli"]);
    map.insert("んうぇ", vec!["nwe", "nwhe", "nule", "nuxe", "nulye", "nuxye", "nwule", "nwuxe", "nwulye", "nwuxye", "nwhule", "nwhuxe", "nwhulye", "nwhuxye", "nnwe", "nnwhe", "nnule", "nnuxe", "nnulye", "nnuxye", "nnwule", "nnwuxe", "nnwulye", "nnwuxye", "nnwhule", "nnwhuxe", "nnwhulye", "nnwhuxye", "xnwe", "xnwhe", "xnule", "xnuxe", "xnulye", "xnuxye", "xnwule", "xnwuxe", "xnwulye", "xnwuxye", "xnwhule", "xnwhuxe", "xnwhulye", "xnwhuxye"]);
    map.insert("んうぉ", vec!["nwho", "nulo", "nuxo", "nwulo", "nwuxo", "nwhulo", "nwhuxo", "nnwho", "nnulo", "nnuxo", "nnwulo", "nnwuxo", "nnwhulo", "nnwhuxo", "xnwho", "xnulo", "xnuxo", "xnwulo", "xnwuxo", "xnwhulo", "xnwhuxo"]);
    map.insert("んゔぁ", vec!["nva", "nvula", "nvuxa", "nnva", "nnvula", "nnvuxa", "xnva", "xnvula", "xnvuxa"]);
    map.insert("んゔぃ", vec!["nvi", "nvyi", "nvuli", "nvuxi", "nvulyi", "nvuxyi", "nnvi", "nnvyi", "nnvuli", "nnvuxi", "nnvulyi", "nnvuxyi", "xnvi", "xnvyi", "xnvuli", "xnvuxi", "xnvulyi", "xnvuxyi"]);
    map.insert("んゔ", vec!["nvu", "nnvu", "xnvu"]);
    map.insert("んゔぇ", vec!["nve", "nvye", "nvule", "nvuxe", "nvulye", "nvuxye", "nnve", "nnvye", "nnvule", "nnvuxe", "nnvulye", "nnvuxye", "xnve", "xnvye", "xnvule", "xnvuxe", "xnvulye", "xnvuxye"]);
    map.insert("んゔぉ", vec!["nvo", "nvulo", "nvuxo", "nnvo", "nnvulo", "nnvuxo", "xnvo", "xnvulo", "xnvuxo"]);
    map.insert("んゔゃ", vec!["nvya", "nvulya", "nvuxya", "nnvya", "nnvulya", "nnvuxya", "xnvya", "xnvulya", "xnvuxya"]);
    map.insert("んゔゅ", vec!["nvyu", "nvulyu", "nvuxyu", "nnvyu", "nnvulyu", "nnvuxyu", "xnvyu", "xnvulyu", "xnvuxyu"]);
    map.insert("んゔょ", vec!["nvyo", "nvulyo", "nvuxyo", "nnvyo", "nnvulyo", "nnvuxyo", "xnvyo", "xnvulyo", "xnvuxyo"]);
    map.insert("んヴぁ", vec!["nva", "nvula", "nvuxa", "nnva", "nnvula", "nnvuxa", "xnva", "xnvula", "xnvuxa"]);
    map.insert("んヴぃ", vec!["nvi", "nvyi", "nvuli", "nvuxi", "nvulyi", "nvuxyi", "nnvi", "nnvyi", "nnvuli", "nnvuxi", "nnvulyi", "nnvuxyi", "xnvi", "xnvyi", "xnvuli", "xnvuxi", "xnvulyi", "xnvuxyi"]);
    map.insert("んヴ", vec!["nvu", "nnvu", "xnvu"]);
    map.insert("んヴぇ", vec!["nve", "nvye", "nvule", "nvuxe", "nvulye", "nvuxye", "nnve", "nnvye", "nnvule", "nnvuxe", "nnvulye", "nnvuxye", "xnve", "xnvye", "xnvule", "xnvuxe", "xnvulye", "xnvuxye"]);
    map.insert("んヴぉ", vec!["nvo", "nvulo", "nvuxo", "nnvo", "nnvulo", "nnvuxo", "xnvo", "xnvulo", "xnvuxo"]);
    map.insert("んヴゃ", vec!["nvya", "nvulya", "nvuxya", "nnvya", "nnvulya", "nnvuxya", "xnvya", "xnvulya", "xnvuxya"]);
    map.insert("んヴゅ", vec!["nvyu", "nvulyu", "nvuxyu", "nnvyu", "nnvulyu", "nnvuxyu", "xnvyu", "xnvulyu", "xnvuxyu"]);
    map.insert("んヴょ", vec!["nvyo", "nvulyo", "nvuxyo", "nnvyo", "nnvulyo", "nnvuxyo", "xnvyo", "xnvulyo", "xnvuxyo"]);
    map.insert("んゐ", vec!["nwyi", "nnwyi", "xnwyi"]);
    map.insert("んゑ", vec!["nwye", "nnwye", "xnwye"]);
    map.insert("ん、", vec!["n,", "nn,", "xn,"]);
    map.insert("っか", vec!["kka", "cca", "ltuka", "xtuka", "ltsuka", "xtsuka", "ltuca", "xtuca", "ltsuca", "xtsuca"]);
    map.insert("っき", vec!["kki", "ltuki", "xtuki", "ltsuki", "xtsuki"]);
    map.insert("っく", vec!["kku", "ccu", "ltuku", "xtuku", "ltsuku", "xtsuku", "ltucu", "xtucu", "ltsucu", "xtsucu"]);
    map.insert("っけ", vec!["kke", "ltuke", "xtuke", "ltsuke", "xtsuke"]);
    map.insert("っこ", vec!["kko", "cco", "ltuko", "xtuko", "ltsuko", "xtsuko", "ltuco", "xtuco", "ltsuco", "xtsuco"]);
    map.insert("っさ", vec!["ssa", "ltusa", "xtusa", "ltsusa", "xtsusa"]);
    map.insert("っし", vec!["ssi", "cci", "sshi", "ltusi", "xtsusi", "ltsusi", "xtsusi", "ltuci", "xtuci", "ltsuci", "xtsuci", "ltushi", "xtushi", "ltsushi", "xtsushi"]);
    map.insert("っす", vec!["ssu", "ltusu", "xtusu", "ltsusu", "xtsusu"]);
    map.insert("っせ", vec!["sse", "cce", "ltuse", "xtuse", "ltsuse", "xtsuse", "ltuce", "xtuce", "ltsuce", "xtsuce"]);
    map.insert("っそ", vec!["sso", "ltuso", "xtuso", "ltsuso", "xtsuso"]);
    map.insert("った", vec!["tta", "ltuta", "xtuta", "ltsuta", "xtsuta"]);
    map.insert("っち", vec!["tti", "cchi", "ltuti", "xtuti", "ltsuti", "xtsuti", "ltuchi", "xtuchi", "ltsuchi", "xtsuchi"]);
    map.insert("っつ", vec!["ttu", "ttsu", "ltutu", "xtutu", "ltsutu", "xtsutu", "ltutsu", "xtutsu", "ltsutsu", "xtsutsu"]);
    map.insert("って", vec!["tte", "ltute", "xtute", "ltsute", "xtsute"]);
    map.insert("っと", vec!["tto", "ltuto", "xtuto", "ltsuto", "xtsuto"]);
    map.insert("っな", vec!["ltuna", "xtuna", "ltsuna", "xtsuna"]);
    map.insert("っに", vec!["ltuni", "xtuni", "ltsuni", "xtsuni"]);
    map.insert("っぬ", vec!["ltunu", "xtunu", "ltsunu", "xtsunu"]);
    map.insert("っね", vec!["ltune", "xtune", "ltsune", "xtsune"]);
    map.insert("っの", vec!["ltuno", "xtuno", "ltsuno", "xtsuno"]);
    map.insert("っは", vec!["hha", "ltuha", "xtuha", "ltsuha", "xtsuha"]);
    map.insert("っひ", vec!["hhi", "ltuhi", "xtuhi", "ltsuhi", "xtsuhi"]);
    map.insert("っふ", vec!["ffu", "hhu", "ltufu", "xtufu", "ltsufu", "xtsufu", "ltuhu", "xtuhu", "ltsuhu", "xtsuhu"]);
    map.insert("っへ", vec!["hhe", "ltuhe", "xtuhe", "ltsuhe", "xtsuhe"]);
    map.insert("っほ", vec!["hho", "ltuho", "xtuho", "ltsuho", "xtsuho"]);
    map.insert("っま", vec!["mma", "ltuma", "xtuma", "ltsuma", "xtsuma"]);
    map.insert("っみ", vec!["mmi", "ltumi", "xtumi", "ltsumi", "xtsumi"]);
    map.insert("っむ", vec!["mmu", "ltumu", "xtumu", "ltsumu", "xtsumu"]);
    map.insert("っめ", vec!["mme", "ltume", "xtume", "ltsume", "xtsume"]);
    map.insert("っも", vec!["mmo", "ltumo", "xtumo", "ltsumo", "xtsumo"]);
    map.insert("っや", vec!["yya", "ltuya", "xtuya", "ltsuya", "xtsuya"]);
    map.insert("っゆ", vec!["yyu", "ltuyu", "xtuyu", "ltsuyu", "xtsuyu"]);
    map.insert("っよ", vec!["yyo", "ltuyo", "xtuyo", "ltsuyo", "xtsuyo"]);
    map.insert("っら", vec!["rra", "ltura", "xtura", "ltsura", "xtsura"]);
    map.insert("っり", vec!["rri", "lturi", "xturi", "ltsuri", "xtsuri"]);
    map.insert("っる", vec!["rru", "lturu", "xturu", "ltsuru", "xtsuru"]);
    map.insert("っれ", vec!["rre", "lture", "xture", "ltsure", "xtsure"]);
    map.insert("っろ", vec!["rro", "lturo", "xturo", "ltsuro", "xtsuro"]);
    map.insert("っわ", vec!["wwa", "ltuwa", "xtuwa", "ltsuwa", "xtsuwa"]);
    map.insert("っを", vec!["wwo", "ltuwo", "xtuwo", "ltsuwo", "xtsuwo"]);
    map.insert("っが", vec!["gga", "ltuga", "xtuga", "ltsuga", "xtsuga"]);
    map.insert("っぎ", vec!["ggi", "ltugi", "xtugi", "ltsugi", "xtsugi"]);
    map.insert("っぐ", vec!["ggu", "ltugu", "xtugu", "ltsugu", "xtsugu"]);
    map.insert("っげ", vec!["gge", "ltuge", "xtuge", "ltsuge", "xtsuge"]);
    map.insert("っご", vec!["ggo", "ltugo", "xtugo", "ltsugo", "xtsugo"]);
    map.insert("っざ", vec!["zza", "ltuza", "xtuza", "ltsuza", "xtsuza"]);
    map.insert("っじ", vec!["jji", "zzi", "ltuji", "xtuji", "ltsuji", "xtsuji", "ltuzi", "xtuzi", "ltsuzi", "xtsuzi"]);
    map.insert("っず", vec!["zzu", "ltuzu", "xtuzu", "ltsuzu", "xtsuzu"]);
    map.insert("っぜ", vec!["zze", "ltuze", "xtuze", "ltsuze", "xtsuze"]);
    map.insert("っぞ", vec!["zzo", "ltuzo", "xtuzo", "ltsuzo", "xtsuzo"]);
    map.insert("っだ", vec!["dda", "ltuda", "xtuda", "ltsuda", "xtsuda"]);
    map.insert("っぢ", vec!["ddi", "ltudi", "xtudi", "ltsudi", "xtsudi"]);
    map.insert("っづ", vec!["ddu", "ltudu", "xtudu", "ltsudu", "xtsudu"]);
    map.insert("っで", vec!["dde", "ltude", "xtude", "ltsude", "xtsude"]);
    map.insert("っど", vec!["ddo", "ltudo", "xtudo", "ltsudo", "xtsudo"]);
    map.insert("っば", vec!["bba", "ltuba", "xtuba", "ltsuba", "xtsuba"]);
    map.insert("っび", vec!["bbi", "ltubi", "xtubi", "ltsubi", "xtsubi"]);
    map.insert("っぶ", vec!["bbu", "ltubu", "xtubu", "ltsubu", "xtsubu"]);
    map.insert("っべ", vec!["bbe", "ltube", "xtube", "ltsube", "xtsube"]);
    map.insert("っぼ", vec!["bbo", "ltubo", "xtubo", "ltsubo", "xtsubo"]);
    map.insert("っぱ", vec!["ppa", "ltupa", "xtupa", "ltsupa", "xtsupa"]);
    map.insert("っぴ", vec!["ppi", "ltupi", "xtupi", "ltsupi", "xtsupi"]);
    map.insert("っぷ", vec!["ppu", "ltupu", "xtupu", "ltsupu", "xtsupu"]);
    map.insert("っぺ", vec!["ppe", "ltupe", "xtupe", "ltsupe", "xtsupe"]);
    map.insert("っぽ", vec!["ppo", "ltupo", "xtupo", "ltsupo", "xtsupo"]);
    map.insert("っきゃ", vec!["kkya", "kkilya", "kkixya", "ltukya", "ltukilya", "ltukixya", "xtukya", "xtukilya", "xtukixya", "ltsukya", "ltsukilya", "ltsukixya", "xtsukya", "xtsukilya", "xtsukixya"]);
    map.insert("っきぃ", vec!["kkyi", "kkili", "kkilyi", "kkixi", "kkixyi", "ltukyi", "ltukili", "ltukilyi", "ltukixi", "ltukixyi", "xtukyi", "xtukili", "xtukilyi", "xtukixi", "xtukixyi", "ltsukyi", "ltsukili", "ltsukilyi", "ltsukixi", "ltsukixyi", "ltsukyi", "xtsukili", "xtsukilyi", "xtsukixi", "xtsukixyi"]);
    map.insert("っきゅ", vec!["kkyu", "kkilyu", "kkixyu", "ltukyu", "ltukilyu", "ltukixyu", "xtukyu", "xtukilyu", "xtukixyu", "ltsukyu", "ltsukilyu", "ltsukixyu", "xtsukyu", "xtsukilyu", "xtsukixyu"]);
    map.insert("っきょ", vec!["kkyo", "kkilyo", "kkixyo", "ltukyo", "xtukyo", "ltsukyo", "xtsukyo", "ltukilyo", "xtukilyo", "ltsukilyo", "xtsukilyo", "ltukixyo", "xtukixyo", "ltsukixyo", "xtsukixyo"]);
    map.insert("っぎゃ", vec!["ggya", "ggilya", "ggixya", "ltugya", "xtugya", "ltsugya", "xtsugya", "ltugilya", "xtugilya", "ltsugilya", "xtsugilya", "ltugixya", "xtugixya", "ltsugixya", "xtsugixya"]);
    map.insert("っぎぃ", vec!["ggyi", "ggili", "ggilyi", "ggixi", "ggixyi", "ltugyi", "xtugyi", "ltsugyi", "xtsugyi", "ltugili", "xtugili", "ltsugili", "xtsugili", "ltugilyi", "xtugilyi", "ltsugilyi", "xtsugilyi", "ltugixi", "xtugixi", "ltsugixi", "xtsugixi", "ltugixyi", "xtugixyi", "ltsugixyi", "xtsugixyi"]);
    map.insert("っぎゅ", vec!["ggyu", "ggilyu", "ggixyu", "ltugyu", "xtugyu", "ltsugyu", "xtsugyu", "ltugilyu", "xtugilyu", "ltsugilyu", "xtsugilyu", "ltugixyu", "xtugixyu", "ltsugixyu", "xtsugixyu"]);
    map.insert("っぎょ", vec!["ggyo", "ggilyo", "ggixyo", "ltugyo", "xtugyo", "ltsugyo", "xtsugyo", "ltugilyo", "xtugilyo", "ltsugilyo", "xtsugilyo", "ltugixyo", "xtugixyo", "ltsugixyo", "xtsugixyo"]);
    map.insert("っしゃ", vec!["ssya", "ssha", "ssilya", "ssixya", "sshilya", "sshixya", "ccilya", "ccixya", "ltusya", "xtusya", "ltsusya", "xtsusya", "ltusha", "xtusha", "ltsusha", "xtsusha", "ltusilya", "xtusilya", "ltsusilya", "xtsusilya", "ltusixya", "xtusixya", "ltsusixya", "xtsusixya", "ltushilya", "xtushilya", "ltsushilya", "xtsushilya", "ltushixya", "xtushixya", "ltsushixya", "xtsushixya", "ltucilya", "xtucilya", "ltsucilya", "xtsucilya", "ltucixya", "xtucixya", "ltsucixya", "xtsucixya"]);
    map.insert("っしぃ", vec!["ssyi", "ssili", "ssixi", "ssilyi", "ssixyi", "sshili", "sshixi", "sshilyi", "sshixyi", "ccili", "ccixi", "ccilyi", "ccixyi", "ltusyi", "xtusyi", "ltsusyi", "xtsusyi", "ltusili", "xtusili", "ltsusili", "xtsusili", "ltusixi", "xtusixi", "ltsusixi", "xtsusixi", "ltusilyi", "xtusilyi", "ltsusilyi", "xtsusilyi", "ltusixyi", "xtusixyi", "ltsusixyi", "xtsusixyi", "ltushili", "xtushili", "ltsushili", "xtsushili", "ltushixi", "xtushixi", "ltsushixi", "xtsushixi", "ltushilyi", "xtushilyi", "ltsushilyi", "xtsushilyi", "ltushixyi", "xtushixyi", "ltsushixyi", "xtsushixyi", "ltucili", "xtucili", "ltsucili", "xtsucili", "ltucixi", "xtucixi", "ltsucixi", "xtsucixi", "ltucilyi", "xtucilyi", "ltsucilyi", "xtsucilyi", "ltucixyi", "xtucixyi", "ltsucixyi", "xtsucixyi"]);
    map.insert("っしゅ", vec!["ssyu", "sshu", "ssilyu", "ssixyu", "sshilyu", "sshixyu", "ccilyu", "ccixyu", "ltusyu", "xtusyu", "ltsusyu", "xtsusyu", "ltushu", "xtushu", "ltsushu", "xtsushu", "ltusilyu", "xtusilyu", "ltsusilyu", "xtsusilyu", "ltusixyu", "xtusixyu", "ltsusixyu", "xtsusixyu", "ltushilyu", "xtushilyu", "ltsushilyu", "xtsushilyu", "ltushixyu", "xtushixyu", "ltsushixyu", "xtsushixyu", "ltucilyu", "xtucilyu", "ltsucilyu", "xtsucilyu", "ltucixyu", "xtucixyu", "ltsucixyu", "xtsucixyu"]);
    map.insert("っしぇ", vec!["ssye", "sshe", "ssile", "ssilye", "ssixe", "ssixye", "sshile", "sshilye", "sshixe", "sshixye", "ccile", "ccilye", "ccixe", "ccixye", "ltusye", "xtusye", "ltsusye", "xtsusye", "ltushe", "xtushe", "ltsushe", "xtsushe", "ltusile", "xtusile", "ltsusile", "xtsusile", "ltusilye", "xtusilye", "ltsusilye", "xtsusilye", "ltusixe", "xtusixe", "ltsusixe", "xtsusixe", "ltusixye", "xtusixye", "ltsusixye", "xtsusixye", "ltushile", "xtushile", "ltsushile", "xtsushile", "ltushilye", "xtushilye", "ltsushilye", "xtsushilye", "ltushixe", "xtushixe", "ltsushixe", "xtsushixe", "ltushixye", "xtushixye", "ltsushixye", "xtsushixye", "ltucile", "xtucile", "ltsucile", "xtsucile", "ltucilye", "xtucilye", "ltsucilye", "xtsucilye", "ltucixe", "xtucixe", "ltsucixe", "xtsucixe", "ltucixye", "xtucixye", "ltsucixye", "xtsucixye"]);
    map.insert("っしょ", vec!["ssyo", "ssho", "ssilyo", "ssixyo", "sshilyo", "sshixyo", "ccilyo", "ccixyo", "ltusyo", "xtusyo", "ltsusyo", "xtsusyo", "ltusho", "xtusho", "ltsusho", "xtsusho", "ltusilyo", "xtusilyo", "ltsusilyo", "xtsusilyo", "ltusixyo", "xtusixyo", "ltsusixyo", "xtsusixyo", "ltushilyo", "xtushilyo", "ltsushilyo", "xtsushilyo", "ltushixyo", "xtushixyo", "ltsushixyo", "xtsushixyo", "ltucilyo", "xtucilyo", "ltsucilyo", "xtsucilyo", "ltucixyo", "xtucixyo", "ltsucixyo", "xtsucixyo"]);
    map.insert("っじゃ", vec!["jja", "jjya", "zzya", "jjilya", "jjixya", "zzilya", "zzixya", "ltuja", "xtuja", "ltsuja", "xtsuja", "ltujya", "xtujya", "ltsujya", "xtsujya", "ltuzya", "xtuzya", "ltsuzya", "xtsuzya", "ltujilya", "xtujilya", "ltsujilya", "xtsujilya", "ltujixya", "xtujixya", "ltsujixya", "xtsujixya", "ltuzilya", "xtuzilya", "ltsuzilya", "xtsuzilya", "ltuzixya", "xtuzixya", "ltsuzixya", "xtsuzixya"]);
    map.insert("っじぃ", vec!["jjyi", "zzyi", "jjili", "jjixi", "jjilyi", "jjixyi", "zzili", "zzixi", "zzilyi", "zzixyi", "ltujyi", "xtujyi", "ltsujyi", "xtsujyi", "ltuzyi", "xtuzyi", "ltsuzyi", "xtsuzyi", "ltujili", "xtujili", "ltsujili", "xtsujili", "ltujixi", "xtujixi", "ltsujixi", "xtsujixi", "ltujilyi", "xtujilyi", "ltsujilyi", "xtsujilyi", "ltujixyi", "xtujixyi", "ltsujixyi", "xtsujixyi", "ltuzili", "xtuzili", "ltsuzili", "xtsuzili", "ltuzixi", "xtuzixi", "ltsuzixi", "xtsuzixi", "ltuzilyi", "xtuzilyi", "ltsuzilyi", "xtsuzilyi", "ltuzixyi", "xtuzixyi", "ltsuzixyi", "xtsuzixyi"]);
    map.insert("っじゅ", vec!["jju", "jjyu", "zzyu", "jjilyu", "jjixyu", "zzilyu", "zzixyu", "ltuju", "xtuju", "ltsuju", "xtsuju", "ltujyu", "xtujyu", "ltsujyu", "xtsujyu", "ltuzyu", "xtuzyu", "ltsuzyu", "xtsuzyu", "ltujilyu", "xtujilyu", "ltsujilyu", "xtsujilyu", "ltujixyu", "xtujixyu", "ltsujixyu", "xtsujixyu", "ltuzilyu", "xtuzilyu", "ltsuzilyu", "xtsuzilyu", "ltuzixyu", "xtuzixyu", "ltsuzixyu", "xtsuzixyu"]);
    map.insert("っじぇ", vec!["jje", "jjye", "zzye", "jjile", "jjixe", "jjilye", "jjixye", "zzile", "zzixe", "zzilye", "zzixye", "ltuje", "xtuje", "ltsuje", "xtsuje", "ltujye", "xtujye", "ltsujye", "xtsujye", "ltuzye", "xtuzye", "ltsuzye", "xtsuzye", "ltujile", "xtujile", "ltsujile", "xtsujile", "ltujixe", "xtujixe", "ltsujixe", "xtsujixe", "ltujilye", "xtujilye", "ltsujilye", "xtsujilye", "ltujixye", "xtujixye", "ltsujixye", "xtsujixye", "ltuzile", "xtuzile", "ltsuzile", "xtsuzile", "ltuzixe", "xtuzixe", "ltsuzixe", "xtsuzixe", "ltuzilye", "xtuzilye", "ltsuzilye", "xtsuzilye", "ltuzixye", "xtuzixye", "ltsuzixye", "xtsuzixye"]);
    map.insert("っじょ", vec!["jjo", "jjyo", "zzyo", "jjilyo", "jjixyo", "zzilyo", "zzixyo", "ltujo", "xtujo", "ltsujo", "xtsujo", "ltujyo", "xtujyo", "ltsujyo", "xtsujyo", "ltuzyo", "xtuzyo", "ltsuzyo", "xtsuzyo", "ltujilyo", "xtujilyo", "ltsujilyo", "xtsujilyo", "ltujixyo", "xtujixyo", "ltsujixyo", "xtsujixyo", "ltuzilyo", "xtuzilyo", "ltsuzilyo", "xtsuzilyo", "ltuzixyo", "xtuzixyo", "ltsuzixyo", "xtsuzixyo"]);
    map.insert("っちゃ", vec!["ttya", "ccha", "ccya", "ttilya", "ttixya", "cchilya", "cchixya", "ltutya", "xtutya", "ltsutya", "xtsutya", "ltucha", "xtucha", "ltsucha", "xtsucha", "ltucya", "xtucya", "ltsucya", "xtsucya", "ltutilya", "xtutilya", "ltsutilya", "xtsutilya", "ltutixya", "xtutixya", "ltsutixya", "xtsutixya", "ltuchilya", "xtuchilya", "ltsuchilya", "xtsuchilya", "ltuchixya", "xtuchixya", "ltsuchixya", "xtsuchixya"]);
    map.insert("っちぃ", vec!["ttyi", "ccyi", "ttili", "ttixi", "ttilyi", "ttixyi", "cchili", "cchixi", "cchilyi", "cchixyi", "ltutyi", "xtutyi", "ltsutyi", "xtsutyi", "ltucyi", "xtucyi", "ltsucyi", "xtsucyi", "ltutili", "xtutili", "ltsutili", "xtsutili", "ltutixi", "xtutixi", "ltsutixi", "xtsutixi", "ltutilyi", "xtutilyi", "ltsutilyi", "xtsutilyi", "ltutixyi", "xtutixyi", "ltsutixyi", "xtsutixyi", "ltuchili", "xtuchili", "ltsuchili", "xtsuchili", "ltuchixi", "xtuchixi", "ltsuchixi", "xtsuchixi", "ltuchilyi", "xtuchilyi", "ltsuchilyi", "xtsuchilyi", "ltuchixyi", "xtuchixyi", "ltsuchixyi", "xtsuchixyi"]);
    map.insert("っちゅ", vec!["ttyu", "cchu", "ccyu", "ttilyu", "ttixyu", "cchilyu", "cchixyu", "ltutyu", "xtutyu", "ltsutyu", "xtsutyu", "ltuchu", "xtuchu", "ltsuchu", "xtsuchu", "ltucyu", "xtucyu", "ltsucyu", "xtsucyu", "ltutilyu", "xtutilyu", "ltsutilyu", "xtsutilyu", "ltutixyu", "xtutixyu", "ltsutixyu", "xtsutixyu", "ltuchilyu", "xtuchilyu", "ltsuchilyu", "xtsuchilyu", "ltuchixyu", "xtuchixyu", "ltsuchixyu", "xtsuchixyu"]);
    map.insert("っちぇ", vec!["ttye", "cche", "ccye", "ttile", "ttixe", "ttilye", "ttixye", "cchile", "cchixe", "cchilye", "cchixye", "ltutye", "xtutye", "ltsutye", "xtsutye", "ltuche", "xtuche", "ltsuche", "xtsuche", "ltucye", "xtucye", "ltsucye", "xtsucye", "ltutile", "xtutile", "ltsutile", "xtsutile", "ltutixe", "xtutixe", "ltsutixe", "xtsutixe", "ltutilye", "xtutilye", "ltsutilye", "xtsutilye", "ltutixye", "xtutixye", "ltsutixye", "xtsutixye", "ltuchile", "xtuchile", "ltsuchile", "xtsuchile", "ltuchixe", "xtuchixe", "ltsuchixe", "xtsuchixe", "ltuchilye", "xtuchilye", "ltsuchilye", "xtsuchilye", "ltuchixye", "xtuchixye", "ltsuchixye", "xtsuchixye"]);
    map.insert("っちょ", vec!["ttyo", "ccho", "ccyo", "ttilyo", "ttixyo", "cchilyo", "cchixyo", "ltutyo", "xtutyo", "ltsutyo", "xtsutyo", "ltucho", "xtucho", "ltsucho", "xtsucho", "ltucyo", "xtucyo", "ltsucyo", "xtsucyo", "ltutilyo", "xtutilyo", "ltsutilyo", "xtsutilyo", "ltutixyo", "xtutixyo", "ltsutixyo", "xtsutixyo", "ltuchilyo", "xtuchilyo", "ltsuchilyo", "xtsuchilyo", "ltuchixyo", "xtuchixyo", "ltsuchixyo", "xtsuchixyo"]);
    map.insert("っぢゃ", vec!["ddya", "ddilya", "ddixya", "ltudya", "xtudya", "ltsudya", "xtsudya", "ltudilya", "xtudilya", "ltsudilya", "xtsudilya", "ltudixya", "xtudixya", "ltsudixya", "xtsudixya"]);
    map.insert("っぢぃ", vec!["ddyi", "ddilyi", "ddixyi", "ltudyi", "xtudyi", "ltsudyi", "xtsudyi", "ltudilyi", "xtudilyi", "ltsudilyi", "xtsudilyi", "ltudixyi", "xtudixyi", "ltsudixyi", "xtsudixyi"]);
    map.insert("っぢゅ", vec!["ddyu", "ddilyu", "ddixyu", "ltudyu", "xtudyu", "ltsudyu", "xtsudyu", "ltudilyu", "xtudilyu", "ltsudilyu", "xtsudilyu", "ltudixyu", "xtudixyu", "ltsudixyu", "xtsudixyu"]);
    map.insert("っぢぇ", vec!["ddye", "ddile", "ddixe", "ddilye", "ddixye", "ltudye", "xtudye", "ltsudye", "xtsudye", "ltudile", "xtudile", "ltsudile", "xtsudile", "ltudixe", "xtudixe", "ltsudixe", "xtsudixe", "ltudilye", "xtudilye", "ltsudilye", "xtsudilye", "ltudixye", "xtudixye", "ltsudixye", "xtsudixye"]);
    map.insert("っぢょ", vec!["ddyo", "ddilyo", "ddixyo", "ltudyo", "xtudyo", "ltsudyo", "xtsudyo", "ltudilyo", "xtudilyo", "ltsudilyo", "xtsudilyo", "ltudixyo", "xtudixyo", "ltsudixyo", "xtsudixyo"]);
    map.insert("っつぁ", vec!["ttsa", "ttula", "ttuxa", "ttsula", "ttsuxa", "ltutsa", "xtutsa", "ltsutsa", "xtsutsa", "ltutula", "xtutula", "ltsutula", "xtsutula", "ltutuxa", "xtutuxa", "ltsutuxa", "xtsutuxa", "ltutsula", "xtutsula", "ltsutsula", "xtsutsula", "ltutsuxa", "xtutsuxa", "ltsutsuxa", "xtsutsuxa"]);
    map.insert("っつぃ", vec!["ttsi", "ttuli", "ttuxi", "ttulyi", "ttuxyi", "ttsuli", "ttsuxi", "ttsulyi", "ttsuxyi", "ltutsi", "xtutsi", "ltsutsi", "xtsutsi", "ltutuli", "xtutuli", "ltsutuli", "xtsutuli", "ltutuxi", "xtutuxi", "ltsutuxi", "xtsutuxi", "ltutulyi", "xtutulyi", "ltsutulyi", "xtsutulyi", "ltutuxyi", "xtutuxyi", "ltsutuxyi", "xtsutuxyi", "ltutsuli", "xtutsuli", "ltsutsuli", "xtsutsuli", "ltutsuxi", "xtutsuxi", "ltsutsuxi", "xtsutsuxi", "ltutsulyi", "xtutsulyi", "ltsutsulyi", "xtsutsulyi", "ltutsuxyi", "xtutsuxyi", "ltsutsuxyi", "xtsutsuxyi"]);
    map.insert("っつぇ", vec!["ttse", "ttule", "ttuxe", "ttulye", "ttuxye", "ttsule", "ttsuxe", "ttsulye", "ttsuxye", "ltutse", "xtutse", "ltsutse", "xtsutse", "ltutule", "xtutule", "ltsutule", "xtsutule", "ltutuxe", "xtutuxe", "ltsutuxe", "xtsutuxe", "ltutulye", "xtutulye", "ltsutulye", "xtsutulye", "ltutuxye", "xtutuxye", "ltsutuxye", "xtsutuxye", "ltutsule", "xtutsule", "ltsutsule", "xtsutsule", "ltutsuxe", "xtutsuxe", "ltsutsuxe", "xtsutsuxe", "ltutsulye", "xtutsulye", "ltsutsulye", "xtsutsulye", "ltutsuxye", "xtutsuxye", "ltsutsuxye", "xtsutsuxye"]);
    map.insert("っつぉ", vec!["ttso", "ttulo", "ttuxo", "ttsulo", "ttsuxo", "ltutso", "xtutso", "ltsutso", "xtsutso", "ltutulo", "xtutulo", "ltsutulo", "xtsutulo", "ltutuxo", "xtutuxo", "ltsutuxo", "xtsutuxo", "ltutsulo", "xtutsulo", "ltsutsulo", "xtsutsulo", "ltutsuxo", "xtutsuxo", "ltsutsuxo", "xtsutsuxo"]);
    map.insert("ってゃ", vec!["ttha", "ttelya", "ttexya", "ltutha", "xtutha", "ltsutha", "xtsutha", "ltutelya", "xtutelya", "ltsutelya", "xtsutelya", "ltutexya", "xtutexya", "ltsutexya", "xtsutexya"]);
    map.insert("ってぃ", vec!["tthi", "tteli", "ttexi", "ttelyi", "ttexyi", "ltuthi", "xtuthi", "ltsuthi", "xtsuthi", "ltuteli", "xtuteli", "ltsuteli", "xtsuteli", "ltutexi", "xtutexi", "ltsutexi", "xtsutexi", "ltutelyi", "xtutelyi", "ltsutelyi", "xtsutelyi", "ltutexyi", "xtutexyi", "ltsutexyi", "xtsutexyi"]);
    map.insert("ってゅ", vec!["tthu", "ttelyu", "ttexyu", "ltuthu", "xtuthu", "ltsuthu", "xtsuthu", "ltutelyu", "xtutelyu", "ltsutelyu", "xtsutelyu", "ltutexyu", "xtutexyu", "ltsutexyu", "xtsutexyu"]);
    map.insert("ってぇ", vec!["tthe", "ttele", "ttexe", "ttelye", "ttexye", "ltuthe", "xtuthe", "ltsuthe", "xtsuthe", "ltutele", "xtutele", "ltsutele", "xtsutele", "ltutexe", "xtutexe", "ltsutexe", "xtsutexe", "ltutelye", "xtutelye", "ltsutelye", "xtsutelye", "ltutexye", "xtutexye", "ltsutexye", "xtsutexye"]);
    map.insert("ってょ", vec!["ttho", "ttelyo", "ttexyo", "ltutho", "xtutho", "ltsutho", "xtsutho", "ltutelyo", "xtutelyo", "ltsutelyo", "xtsutelyo", "ltutexyo", "xtutexyo", "ltsutexyo", "xtsutexyo"]);
    map.insert("っでゃ", vec!["ddha", "ddelya", "ddexya", "ltudha", "xtudha", "ltsudha", "xtsudha", "ltudelya", "xtudelya", "ltsudelya", "xtsudelya", "ltudexya", "xtudexya", "ltsudexya", "xtsudexya"]);
    map.insert("っでぃ", vec!["ddhi", "ddeli", "ddexi", "ddelyi", "ddexyi", "ltudhi", "xtudhi", "ltsudhi", "xtsudhi", "ltudeli", "xtudeli", "ltsudeli", "xtsudeli", "ltudexi", "xtudexi", "ltsudexi", "xtsudexi", "ltudelyi", "xtudelyi", "ltsudelyi", "xtsudelyi", "ltudexyi", "xtudexyi", "ltsudexyi", "xtsudexyi"]);
    map.insert("っでゅ", vec!["ddhu", "ddelyu", "ddexyu", "ltudhu", "xtudhu", "ltsudhu", "xtsudhu", "ltudelyu", "xtudelyu", "ltsudelyu", "xtsudelyu", "ltudexyu", "xtudexyu", "ltsudexyu", "xtsudexyu"]);
    map.insert("っでぇ", vec!["ddhe", "ddele", "ddexe", "ddelye", "ddexye", "ltudhe", "xtudhe", "ltsudhe", "xtsudhe", "ltudele", "xtudele", "ltsudele", "xtsudele", "ltudexe", "xtudexe", "ltsudexe", "xtsudexe", "ltudelye", "xtudelye", "ltsudelye", "xtsudelye", "ltudexye", "xtudexye", "ltsudexye", "xtsudexye"]);
    map.insert("っでょ", vec!["ddho", "ddelyo", "ddexyo", "ltudho", "xtudho", "ltsudho", "xtsudho", "ltudelyo", "xtudelyo", "ltsudelyo", "xtsudelyo", "ltudexyo", "xtudexyo", "ltsudexyo", "xtsudexyo"]);
    map.insert("っぴゃ", vec!["ppya", "ppilya", "ppixya", "ltupya", "xtupya", "ltsupya", "xtsupya", "ltupilya", "xtupilya", "ltsupilya", "xtsupilya", "ltupixya", "xtupixya", "ltsupixya", "xtsupixya"]);
    map.insert("っぴぃ", vec!["ppyi", "ppili", "ppixi", "ppilyi", "ppixyi", "ltupyi", "xtupyi", "ltsupyi", "xtsupyi", "ltupili", "xtupili", "ltsupili", "xtsupili", "ltupixi", "xtupixi", "ltsupixi", "xtsupixi", "ltupilyi", "xtupilyi", "ltsupilyi", "xtsupilyi", "ltupixyi", "xtupixyi", "ltsupixyi", "xtsupixyi"]);
    map.insert("っぴゅ", vec!["ppyu", "ppilyu", "ppixyu", "ltupyu", "xtupyu", "ltsupyu", "xtsupyu", "ltupilyu", "xtupilyu", "ltsupilyu", "xtsupilyu", "ltupixyu", "xtupixyu", "ltsupixyu", "xtsupixyu"]);
    map.insert("っぴぇ", vec!["ppye", "ppile", "ppixe", "ppilye", "ppixye", "ltupye", "xtupye", "ltsupye", "xtsupye", "ltupile", "xtupile", "ltsupile", "xtsupile", "ltupixe", "xtupixe", "ltsupixe", "xtsupixe", "ltupilye", "xtupilye", "ltsupilye", "xtsupilye", "ltupixye", "xtupixye", "ltsupixye", "xtsupixye"]);
    map.insert("っぴょ", vec!["ppyo", "ppilyo", "ppixyo", "ltupyo", "xtupyo", "ltsupyo", "xtsupyo", "ltupilyo", "xtupilyo", "ltsupilyo", "xtsupilyo", "ltupixyo", "xtupixyo", "ltsupixyo", "xtsupixyo"]);
    map.insert("っひゃ", vec!["hhya", "hhilya", "hhixya", "ltuhya", "xtuhya", "ltsuhya", "xtsuhya", "ltuhilya", "xtuhilya", "ltsuhilya", "xtsuhilya", "ltuhixya", "xtuhixya", "ltsuhixya", "xtsuhixya"]);
    map.insert("っひぃ", vec!["hhyi", "hhili", "hhixi", "hhilyi", "hhixyi", "ltuhyi", "xtuhyi", "ltsuhyi", "xtsuhyi", "ltuhili", "xtuhili", "ltsuhili", "xtsuhili", "ltuhixi", "xtuhixi", "ltsuhixi", "xtsuhixi", "ltuhilyi", "xtuhilyi", "ltsuhilyi", "xtsuhilyi", "ltuhixyi", "xtuhixyi", "ltsuhixyi", "xtsuhixyi"]);
    map.insert("っひゅ", vec!["hhyu", "hhilyu", "hhixyu", "ltuhyu", "xtuhyu", "ltsuhyu", "xtsuhyu", "ltuhilyu", "xtuhilyu", "ltsuhilyu", "xtsuhilyu", "ltuhixyu", "xtuhixyu", "ltsuhixyu", "xtsuhixyu"]);
    map.insert("っひぇ", vec!["hhye", "hhile", "hhixe", "hhilye", "hhixye", "ltuhye", "xtuhye", "ltsuhye", "xtsuhye", "ltuhile", "xtuhile", "ltsuhile", "xtsuhile", "ltuhixe", "xtuhixe", "ltsuhixe", "xtsuhixe", "ltuhilye", "xtuhilye", "ltsuhilye", "xtsuhilye", "ltuhixye", "xtuhixye", "ltsuhixye", "xtsuhixye"]);
    map.insert("っひょ", vec!["hhyo", "hhilyo", "hhixyo", "ltuhyo", "xtuhyo", "ltsuhyo", "xtsuhyo", "ltuhilyo", "xtuhilyo", "ltsuhilyo", "xtsuhilyo", "ltuhixyo", "xtuhixyo", "ltsuhixyo", "xtsuhixyo"]);
    map.insert("っびゃ", vec!["bbya", "bbilya", "bbixya", "ltubya", "xtubya", "ltsubya", "xtsubya", "ltubilya", "xtubilya", "ltsubilya", "xtsubilya", "ltubixya", "xtubixya", "ltsubixya", "xtsubixya"]);
    map.insert("っびぃ", vec!["bbyi", "bbili", "bbixi", "bbilyi", "bbixyi", "ltubyi", "xtubyi", "ltsubyi", "xtsubyi", "ltubili", "xtubili", "ltsubili", "xtsubili", "ltubixi", "xtubixi", "ltsubixi", "xtsubixi", "ltubilyi", "xtubilyi", "ltsubilyi", "xtsubilyi", "ltubixyi", "xtubixyi", "ltsubixyi", "xtsubixyi"]);
    map.insert("っびゅ", vec!["bbyu", "bbilyu", "bbixyu", "ltubyu", "xtubyu", "ltsubyu", "xtsubyu", "ltubilyu", "xtubilyu", "ltsubilyu", "xtsubilyu", "ltubixyu", "xtubixyu", "ltsubixyu", "xtsubixyu"]);
    map.insert("っびぇ", vec!["bbye", "bbile", "bbixe", "bbilye", "bbixye", "ltubye", "xtubye", "ltsubye", "xtsubye", "ltubile", "xtubile", "ltsubile", "xtsubile", "ltubixe", "xtubixe", "ltsubixe", "xtsubixe", "ltubilye", "xtubilye", "ltsubilye", "xtsubilye", "ltubixye", "xtubixye", "ltsubixye", "xtsubixye"]);
    map.insert("っびょ", vec!["bbyo", "bbilyo", "bbixyo", "ltubyo", "xtubyo", "ltsubyo", "xtsubyo", "ltubilyo", "xtubilyo", "ltsubilyo", "xtsubilyo", "ltubixyo", "xtubixyo", "ltsubixyo", "xtsubixyo"]);
    map.insert("っふぁ", vec!["ffa", "ffula", "ffuxa", "hhula", "hhuxa", "ltufa", "xtufa", "ltsufa", "xtsufa", "ltufula", "xtufula", "ltsufula", "xtsufula", "ltufuxa", "xtufuxa", "ltsufuxa", "xtsufuxa", "ltuhula", "xtuhula", "ltsuhula", "xtsuhula", "ltuhuxa", "xtuhuxa", "ltsuhuxa", "xtsuhuxa"]);
    map.insert("っふぃ", vec!["ffi", "ffyi", "ffuli", "ffuxi", "ffulyi", "ffuxyi", "hhuli", "hhuxi", "hhulyi", "hhuxyi", "ltufi", "xtufi", "ltsufi", "xtsufi", "ltufyi", "xtufyi", "ltsufyi", "xtsufyi", "ltufuli", "xtufuli", "ltsufuli", "xtsufuli", "ltufuxi", "xtufuxi", "ltsufuxi", "xtsufuxi", "ltufulyi", "xtufulyi", "ltsufulyi", "xtsufulyi", "ltufuxyi", "xtufuxyi", "ltsufuxyi", "xtsufuxyi", "ltuhuli", "xtuhuli", "ltsuhuli", "xtsuhuli", "ltuhuxi", "xtuhuxi", "ltsuhuxi", "xtsuhuxi", "ltuhulyi", "xtuhulyi", "ltsuhulyi", "xtsuhulyi", "ltuhuxyi", "xtuhuxyi", "ltsuhuxyi", "xtsuhuxyi"]);
    map.insert("っふぇ", vec!["ffe", "ffye", "ffule", "ffuxe", "ffulye", "ffuxye", "hhule", "hhuxe", "hhulye", "hhuxye", "ltufe", "xtufe", "ltsufe", "xtsufe", "ltufye", "xtufye", "ltsufye", "xtsufye", "ltufule", "xtufule", "ltsufule", "xtsufule", "ltufuxe", "xtufuxe", "ltsufuxe", "xtsufuxe", "ltufulye", "xtufulye", "ltsufulye", "xtsufulye", "ltufuxye", "xtufuxye", "ltsufuxye", "xtsufuxye", "ltuhule", "xtuhule", "ltsuhule", "xtsuhule", "ltuhuxe", "xtuhuxe", "ltsuhuxe", "xtsuhuxe", "ltuhulye", "xtuhulye", "ltsuhulye", "xtsuhulye", "ltuhuxye", "xtuhuxye", "ltsuhuxye", "xtsuhuxye"]);
    map.insert("っふぉ", vec!["ffo", "ffulo", "ffuxo", "hhulo", "hhuxo", "ltufo", "xtufo", "ltsufo", "xtsufo", "ltufulo", "xtufulo", "ltsufulo", "xtsufulo", "ltufuxo", "xtufuxo", "ltsufuxo", "xtsufuxo", "ltuhulo", "xtuhulo", "ltsuhulo", "xtsuhulo", "ltuhuxo", "xtuhuxo", "ltsuhuxo", "xtsuhuxo"]);
    map.insert("っみゃ", vec!["mmya", "mmilya", "mmixya", "ltumya", "xtumya", "ltsumya", "xtsumya", "ltumilya", "xtumilya", "ltsumilya", "xtsumilya", "ltumixya", "xtumixya", "ltsumixya", "xtsumixya"]);
    map.insert("っみぃ", vec!["mmyi", "mmili", "mmixi", "mmilyi", "mmixyi", "ltumyi", "xtumyi", "ltsumyi", "xtsumyi", "ltumili", "xtumili", "ltsumili", "xtsumili", "ltumixi", "xtumixi", "ltsumixi", "xtsumixi", "ltumilyi", "xtumilyi", "ltsumilyi", "xtsumilyi", "ltumixyi", "xtumixyi", "ltsumixyi", "xtsumixyi"]);
    map.insert("っみゅ", vec!["mmyu", "mmilyu", "mmixyu", "ltumyu", "xtumyu", "ltsumyu", "xtsumyu", "ltumilyu", "xtumilyu", "ltsumilyu", "xtsumilyu", "ltumixyu", "xtumixyu", "ltsumixyu", "xtsumixyu"]);
    map.insert("っみぇ", vec!["mmye", "mmile", "mmixe", "mmilye", "mmixye", "ltumye", "xtumye", "ltsumye", "xtsumye", "ltumile", "xtumile", "ltsumile", "xtsumile", "ltumixe", "xtumixe", "ltsumixe", "xtsumixe", "ltumilye", "xtumilye", "ltsumilye", "xtsumilye", "ltumixye", "xtumixye", "ltsumixye", "xtsumixye"]);
    map.insert("っみょ", vec!["mmyo", "mmilyo", "mmixyo", "ltumyo", "xtumyo", "ltsumyo", "xtsumyo", "ltumilyo", "xtumilyo", "ltsumilyo", "xtsumilyo", "ltumixyo", "xtumixyo", "ltsumixyo", "xtsumixyo"]);
    map.insert("っりゃ", vec!["rrya", "rrilya", "rrixya", "lturya", "xturya", "ltsurya", "xtsurya", "lturilya", "xturilya", "ltsurilya", "xtsurilya", "lturixya", "xturixya", "ltsurixya", "xtsurixya"]);
    map.insert("っりぃ", vec!["rryi", "rrili", "rrixi", "rrilyi", "rrixyi", "lturyi", "xturyi", "ltsuryi", "xtsuryi", "lturili", "xturili", "ltsurili", "xtsurili", "lturixi", "xturixi", "ltsurixi", "xtsurixi", "lturilyi", "xturilyi", "ltsurilyi", "xtsurilyi", "lturixyi", "xturixyi", "ltsurixyi", "xtsurixyi"]);
    map.insert("っりゅ", vec!["rryu", "rrilyu", "rrixyu", "lturyu", "xturyu", "ltsuryu", "xtsuryu", "lturilyu", "xturilyu", "ltsurilyu", "xtsurilyu", "lturixyu", "xturixyu", "ltsurixyu", "xtsurixyu"]);
    map.insert("っりぇ", vec!["rrye", "rrile", "rrixe", "rrilye", "rrixye", "lturye", "xturye", "ltsurye", "xtsurye", "lturile", "xturile", "ltsurile", "xtsurile", "lturixe", "xturixe", "ltsurixe", "xtsurixe", "lturilye", "xturilye", "ltsurilye", "xtsurilye", "lturixye", "xturixye", "ltsurixye", "xtsurixye"]);
    map.insert("っりょ", vec!["rryo", "rrilyo", "rrixyo", "lturyo", "xturyo", "ltsuryo", "xtsuryo", "lturilyo", "xturilyo", "ltsurilyo", "xtsurilyo", "lturixyo", "xturixyo", "ltsurixyo", "xtsurixyo"]);
    map.insert("ー", vec!["-"]);
    map.insert("、", vec![","]);
    map.insert("。", vec!["."]);
    map.insert("0", vec!["0"]);
    map.insert("1", vec!["1"]);
    map.insert("2", vec!["2"]);
    map.insert("3", vec!["3"]);
    map.insert("4", vec!["4"]);
    map.insert("5", vec!["5"]);
    map.insert("6", vec!["6"]);
    map.insert("7", vec!["7"]);
    map.insert("8", vec!["8"]);
    map.insert("9", vec!["9"]);
    map.insert("a", vec!["a"]);
    map.insert("b", vec!["b"]);
    map.insert("c", vec!["c"]);
    map.insert("d", vec!["d"]);
    map.insert("e", vec!["e"]);
    map.insert("f", vec!["f"]);
    map.insert("g", vec!["g"]);
    map.insert("h", vec!["h"]);
    map.insert("i", vec!["i"]);
    map.insert("j", vec!["j"]);
    map.insert("k", vec!["k"]);
    map.insert("l", vec!["l"]);
    map.insert("m", vec!["m"]);
    map.insert("n", vec!["n"]);
    map.insert("o", vec!["o"]);
    map.insert("p", vec!["p"]);
    map.insert("q", vec!["q"]);
    map.insert("r", vec!["r"]);
    map.insert("s", vec!["s"]);
    map.insert("t", vec!["t"]);
    map.insert("u", vec!["u"]);
    map.insert("v", vec!["v"]);
    map.insert("w", vec!["w"]);
    map.insert("x", vec!["x"]);
    map.insert("y", vec!["y"]);
    map.insert("z", vec!["z"]);
    map.insert("A", vec!["A"]);
    map.insert("B", vec!["B"]);
    map.insert("C", vec!["C"]);
    map.insert("D", vec!["D"]);
    map.insert("E", vec!["E"]);
    map.insert("F", vec!["F"]);
    map.insert("G", vec!["G"]);
    map.insert("H", vec!["H"]);
    map.insert("I", vec!["I"]);
    map.insert("J", vec!["J"]);
    map.insert("K", vec!["K"]);
    map.insert("L", vec!["L"]);
    map.insert("M", vec!["M"]);
    map.insert("N", vec!["N"]);
    map.insert("O", vec!["O"]);
    map.insert("P", vec!["P"]);
    map.insert("Q", vec!["Q"]);
    map.insert("R", vec!["R"]);
    map.insert("S", vec!["S"]);
    map.insert("T", vec!["T"]);
    map.insert("U", vec!["U"]);
    map.insert("V", vec!["V"]);
    map.insert("W", vec!["W"]);
    map.insert("X", vec!["X"]);
    map.insert("Y", vec!["Y"]);
    map.insert("Z", vec!["Z"]);
    map.insert(" ", vec![" "]);
    map.insert(",", vec![","]);
    map.insert(".", vec!["."]);
    map.insert("んa", vec!["nna", "xna"]);
    map.insert("んb", vec!["nnb", "xnb"]);
    map.insert("んc", vec!["nnc", "xnc"]);
    map.insert("んd", vec!["nnd", "xnd"]);
    map.insert("んe", vec!["nne", "xne"]);
    map.insert("んf", vec!["nnf", "xnf"]);
    map.insert("んg", vec!["nng", "xng"]);
    map.insert("んh", vec!["nnh", "xnh"]);
    map.insert("んi", vec!["nni", "xni"]);
    map.insert("んj", vec!["nnj", "xnj"]);
    map.insert("んk", vec!["nnk", "xnk"]);
    map.insert("んl", vec!["nnl", "xnl"]);
    map.insert("んm", vec!["nnm", "xnm"]);
    map.insert("んn", vec!["nnn", "xnn"]);
    map.insert("んo", vec!["nno", "xno"]);
    map.insert("んp", vec!["nnp", "xnp"]);
    map.insert("んq", vec!["nnq", "xnq"]);
    map.insert("んr", vec!["nnr", "xnr"]);
    map.insert("んs", vec!["nns", "xns"]);
    map.insert("んt", vec!["nnt", "xnt"]);
    map.insert("んu", vec!["nnu", "xnu"]);
    map.insert("んv", vec!["nnv", "xnv"]);
    map.insert("んw", vec!["nnw", "xnw"]);
    map.insert("んx", vec!["nnx", "xnx"]);
    map.insert("んy", vec!["nny", "xny"]);
    map.insert("んz", vec!["nnz", "xnz"]);
    map.insert("んA", vec!["nnA", "xnA"]);
    map.insert("んB", vec!["nnB", "xnB"]);
    map.insert("んC", vec!["nnC", "xnC"]);
    map.insert("んD", vec!["nnD", "xnD"]);
    map.insert("んE", vec!["nnE", "xnE"]);
    map.insert("んF", vec!["nnF", "xnF"]);
    map.insert("んG", vec!["nnG", "xnG"]);
    map.insert("んH", vec!["nnH", "xnH"]);
    map.insert("んI", vec!["nnI", "xnI"]);
    map.insert("んJ", vec!["nnJ", "xnJ"]);
    map.insert("んK", vec!["nnK", "xnK"]);
    map.insert("んL", vec!["nnL", "xnL"]);
    map.insert("んM", vec!["nnM", "xnM"]);
    map.insert("んN", vec!["nnN", "xnN"]);
    map.insert("んO", vec!["nnO", "xnO"]);
    map.insert("んP", vec!["nnP", "xnP"]);
    map.insert("んQ", vec!["nnQ", "xnQ"]);
    map.insert("んR", vec!["nnR", "xnR"]);
    map.insert("んS", vec!["nnS", "xnS"]);
    map.insert("んT", vec!["nnT", "xnT"]);
    map.insert("んU", vec!["nnU", "xnU"]);
    map.insert("んV", vec!["nnV", "xnV"]);
    map.insert("んW", vec!["nnW", "xnW"]);
    map.insert("んX", vec!["nnX", "xnX"]);
    map.insert("んY", vec!["nnY", "xnY"]);
    map.insert("んZ", vec!["nnZ", "xnZ"]);

    map
}